### ISSUE TITLE
Discord4J#disableChannelWarnings() should disable 404 Errors

### ISSUE THREAD

**Issue by robot-rover** [austinv11/Discord4J#113]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
When I delete a message with my bot, I get a 404 error even if I don't access it anymore, and it leads to this maddness: http://hastebin.com/hadasoqexu

### Steps to Reproduce
1. Delete a message with Discord4J
2. Wait

...

**Expected behavior:** Silence 404 Errors

**Actual behavior:** Tons of 404 Errors flood the logs

**Stacktrace (if applicable):** http://hastebin.com/hadasoqexu

**Version affected:** Current Dev Build (dev-2.5.4-g2f1495c-91)

### Additional Information
I think the fact that it doesn't realize the Message has been deleted and trys to access it could be a bug as well, but I don't know. Yes I have tripple checked that my code does not access the IMessage object after deleting it. All references to the object are removed after deleting it.

**Comment by GrandPanda** [comment]
Cannot recreate. 
```java
try {
    client.getMessageById("xxx").delete();
} catch (MissingPermissionsException | DiscordException | RateLimitException e) {
	e.printStackTrace();
}
```
Does not produce any 404s.

**Comment by theIglooo** [comment]
[Also cannot recreate](http://hastebin.com/uripovivax)
Those are also multiple different messages in different channels

**Comment by robot-rover** [comment]
well then I am in for a fun night of debugging...
