### ISSUE TITLE
Connecting to Voice Channel Creates Memory Leaks

### ISSUE THREAD

**Issue by robot-rover** [austinv11/Discord4J#114]
### Prerequisites
- [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
- [x] This issue specifically has something to do with Discord4J
- [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
  already
### Description

When you connect to a voice channel it creates 9 threads that are never cleaned up.
### Steps to Reproduce
1. Connect to a voice channel
2. Disconnect
3. Measure the ammount of threads
4. Repeat

TheIgloo has confirmed he is able to reproduce this

...

**Expected behavior:** When disconnecting from a voice channel the connection's threads are cleaned up.

**Actual behavior:** The threads are never cleaned up, not even when calling the Garbage Collector.

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]
I made a bot to test this. It is a blank bot that simply connects to a voiceChannel, disconnects, and measures the amount of threads present 10 x, then measures the amount of threads every 15 seconds.
Here is the output: http://hastebin.com/ogixonadet.py
**Version affected:** Current Dev build
### Additional Information

TheIgloo tested this as well and he found the same thing. I have also looked at the threads with VisualVM and they are infact at the levels that are being output.

**Comment by ArsenArsen** [comment]
I am pretty sure this is not fixed. After seeing thousands of threads on FlareBot I ran the same test. It quickly went over 500 threads. Here's that threaddump http://hastebin.com/miwaxuqona.pl

**Comment by robot-rover** [comment]
Good so I'm not going insane then
