### ISSUE TITLE
NullPointer in DiscordWS

### ISSUE THREAD

**Issue by rskupnik** [austinv11/Discord4J#131]
NullPointer is thrown in DiscordWS @ line 164 (onOpen function), because client.token.isEmpty() is called without checking if client.token is null.

**Comment by ArsenArsen** [comment]
Any stack trace would be really useful.

**Comment by BrutalCSkakan** [comment]
I've been struggling with this too, seems to happen a bit random

**Comment by bwfcwalshyPluginDev** [comment]
Why are you even not using a token? The login will be removed in 2.7. It has also been deprecated for a while. I highly suggest you use the token.

**Comment by ArsenArsen** [comment]
Also, please update, the line you mentioned is a closed bracket in dev and master.
