### ISSUE TITLE
403 Forbidden Error / IllegalArgumentException

### ISSUE THREAD

**Issue by glitchedcoder** [austinv11/Discord4J#132]
### Prerequisites

- [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
- [x] This issue specifically has something to do with Discord4J
- [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
I tried running my bot about 3 days ago and this error appeared for some odd reason. Couldn't figure out what was going wrong.

### Steps to Reproduce
1. Login with the bot
2. Error is thrown

**Expected behavior:** Supposed to login and do tasks.

**Actual behavior:** Didn't login, bot may go online for 1 minute then time out.

**Stacktrace (if applicable):** http://pastebin.com/N71gc3iQ

**Version affected:** 2.5.1

**Comment by GrandPanda** [comment]
2.5.1 is not a supported version. Please update.
