### ISSUE TITLE
discord4j doesn't work on outdated operating systems

### ISSUE THREAD

**Issue by weeryan17** [austinv11/Discord4J#135]
### Prerequisites
- [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
- [x] This issue specifically has something to do with Discord4J
- [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
  already
### Description

So I'm using discord4j to make a minecraft plugin that links groups on the server the roles in discord, and when using a host call mc prohosting it randomly breaks. I've gotten it to work on all of my operating systems. However i have had other people test it with mc prohosting and it doesn't work so it's not just my server.
### Steps to Reproduce

Don't have any because not 100% sure of cause

...

**Expected behavior:** 
When it's working my bot starts up and sends a chat message saying "Bot ready to do stuff!" and starts linking minecraft groups to discord roles.

**Actual behavior:** 
On mc prohosting it crashes and determine that the guild is unlivable. I think it however is about to connect for a second or two.

**Stacktrace (if applicable):** [pastebin](http://pastebin.com/58aavEj8)

**Version affected:**
2.5.4
2.6.0
### Additional Information

here is a forum on another site that has to do with this: [link](https://forums.mcprohosting.com/threads/discord4j-api-in-plugins-not-working-on-mcpro-server.19732/)
I know it isn't the best issue report but I can't effectively reproduce it or find out the exact problem

**Comment by robot-rover** [comment]
Sorry but it looks to me like it is a problem on your end:
`The UnsatisfiedLinkError is thrown when an application attempts to load a native library like .so in Linux, .dll on Windows or .dylib in Mac and that library does not exist. Specifically, in order to find the required native library, the JVM looks in both the PATH environment variable and the java.library.path system property.`
Source - [JavaCodeGeeks](https://examples.javacodegeeks.com/java-basics/exceptions/java-lang-unsatisfiedlinkerror-how-to-handle-unsatisfied-link-error/)
Ur apparently missing some internal OS libraries that the JVM uses

**Comment by GrandPanda** [comment]
#74 is related. I will be replacing the current native binaries with ones that are compatible with older systems soon. If you need this ASAP, you can clone the repo and replace them yourself. I'm not sure when I will be able to replace them on a stable version.

**Comment by weeryan17** [comment]
@GrandPanda Thank you. I don't really need them soon so I'll be fine till next release.

**Comment by manuelgu** [comment]
@weeryan17 I might be wrong, but in case you don't need any of the audio/voice features, you may call `Discord4j#disableAudio()` to fix this.

**Comment by weeryan17** [comment]
@manuelgu well that actually work. thank you for the help. I still hope this get fixed so that i have the option to use audio in the future but for now it works
