### ISSUE TITLE
Unknown message received: CHANNEL_PINS_ACK

### ISSUE THREAD

**Issue by NorbiPeti** [austinv11/Discord4J#139]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
After pinning a message, I get this message.

### Steps to Reproduce
1. Obtain channel and message objects
2. channel.pin(message);

...

**Expected behavior:** No warnings to appear.

**Actual behavior:** The message got pinned and I got this warning:

> [17:02:54 WARN]: Unknown message received: CHANNEL_PINS_ACK, REPORT THIS TO THE DISCORD4J DEV! (ignoring): {"t":"CHANNEL_PINS_ACK","s":1507,"op":0,"d":{"timestamp":"2016-10-21T21:02:54.366077+00:00","channel_id":"125813020357165056"}}

**Stacktrace (if applicable):** -

**Version affected:** 2.6.1

### Additional Information
-

**Comment by decyg** [comment]
Are you using a user account (email and password) or a bot token?

**Comment by GrandPanda** [comment]
Bot accounts receive this event by mistake. Confirmed bug by Discord.
