### ISSUE TITLE
Unknown message

### ISSUE THREAD

**Issue by hazeluff** [austinv11/Discord4J#140]
`04:26:57.344: [WARN][WebSocketClient@42544488-21][sx.blah.discord.Discord4J] - Unknown message received: CHANNEL_PINS_ACK, REPORT THIS TO THE DISCORD4J DEV! (ignoring): {"t":"CHANNEL_PINS_ACK","s":6,"op":0,"d":{"timestamp":"2016-10-22T11:26:58.788010+00:00","channel_id":"239348872445558784"}}`

**Comment by ArsenArsen** [comment]
Bug with Discord itself, not Discord4J. Also improperly formatted.

Can be safely ignored.

**Comment by GrandPanda** [comment]
See #139. If Discord doesn't fix this by the time I merge websocket-rewrite, I will add something to ignore this event, but until then, it can be safely ignored on your end.
