### ISSUE TITLE
IndexOutOfBoundsException in AudioPlayer

### ISSUE THREAD

**Issue by Tomhoogstra** [austinv11/Discord4J#142]
### Prerequisites

Using this WAV file: http://puu.sh/rWewE.wav
### Description

When attempting to add this file to the queue, I get spammed with the same (slightly changing) error. 
File was downloaded using youtube-dl.py and the following code:

PrintWriter writer = new PrintWriter("youtube-dl.bat", "UTF-8");
writer.println("youtube-dl.py " + newURL + " --extract-audio --audio-format wav --output /Songs/test.wav");
writer.close();

Process process = Runtime.getRuntime().exec("youtube-dl.bat");
process.waitFor();
process.destroy();
### Steps to Reproduce

Attempt to add that file to the audio player queue

...

**Expected behavior:** Audio is played

**Actual behavior:** Error Spam

**Stacktrace (if applicable):** 
http://pastebin.com/vG46J3de

**Version affected:** 2.6.1
### Additional Information

Tried both MP3 and WAV files. Audio player has worked fine with other files I have downloaded.

**Comment by ArsenArsen** [comment]
Post youtube-dl.bat

**Comment by bwfcwalshyPluginDev** [comment]
D4J does not support WAV files, show us the MP3 attempt.

**Comment by ArsenArsen** [comment]
Also, youtube-dl.py is not an executable. Also look into ProcessBuilders

**Comment by Tomhoogstra** [comment]
Using http://puu.sh/rWfa9.mp3
http://pastebin.com/NjuRB1S0

**Comment by Tomhoogstra** [comment]
@ArsenArsen I'm executing youtube-dl.bat, which runs youtube-dl.py with the correct arguments.

**Comment by theIglooo** [comment]
What's your actual version? Snapshot changes depending on when you last reimported, and latest could mean latest release, latest dev, latest websocket-rewrite, etc.

**Comment by ArsenArsen** [comment]
@Tomhoogstra Use ProcessBuilder. Eg:
`ProcessBuilder processBuilder = new ProcessBuilder("python", "youtube-dl.py", newUrl, ...)`
Gives alot more control and won't break with spaces

**Comment by Tomhoogstra** [comment]
@theIglooo Discord4j-2.6.1

@ArsenArsen Yeah ill go ahead and change it up, but I don't think its causing my problem as it has previously worked fine with other videos

**Comment by theIglooo** [comment]
![Image of error](https://u.pomf.is/oiwroa.png)
I can't even play your file outside of D4J

**Comment by Tomhoogstra** [comment]
@theIglooo I have no issues running it in Windows Media Player

**Comment by Tomhoogstra** [comment]
Issue seems to be related to file downloaded by youtube-dl
Regardless, some better error handling could be in place here
