### ISSUE TITLE
Don't Disturb Mode doesn't work

### ISSUE THREAD

**Issue by galaxyoyo** [austinv11/Discord4J#145]
### Description
It is impossible for me to put my bot in DND mode. When I try to do this, it becomes online.

### Steps to Reproduce
client.changePresence(Presences.DND);
That's all

**Expected behavior:** Presence switched to DND

**Actual behavior:** Presence switched to Online

**Stacktrace (if applicable):** No Stacktrace (it’s a bug and not an exception)

**Version affected:** 2.6.1 (latest)

### Additional Information
When the DND mode was implemented, the Method DiscordClientImpl#updatePresence(boolean, Status) wasn't editted. I think the error is here.

**Comment by ArsenArsen** [comment]
Was this done in the ReadyEvent?

**Comment by chrislo27** [comment]
Changing presences other than online, idle, or streaming is part of the v6 websocket, and the documentation for that is not out yet. This is on our internal to-do list, but thanks for reporting it.
