### ISSUE TITLE
Edited roles hierarchy is too high.

### ISSUE THREAD

**Issue by SamboyCoding** [austinv11/Discord4J#149]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I'm trying to create a role with my bot. I'm using the following code:
```
RoleBuilder build = new RoleBuilder(serv).withName("rankname").withColor(Color.darkGray).setMentionable(false).setHoist(false)
IRole role = build.build();
```

The bot has every permission, and I mean all of them. It's at the top of the hierarchy, but I still get "Edited roles hierarchy is too high."

### Steps to Reproduce
1. Create a bot
2. In the ready event listener, add the above code
3. Run the bot, and get an error

...

**Expected behavior:**
The rank would be created with the specified name and colour.
**Actual behavior:**
I get an error,  and the rank is created but with the default name and colour. 
**Stacktrace (if applicable):** 
http://hastebin.com/raw/uvexapaviy
**Version affected:**
2.6.1

**Comment by SamboyCoding** [comment]
I think I've got some more info. I created a rank manually,  and outputted its position,  and the position of my bot's rank, and they were both 1. Firstly,  this shouldn't happen, and secondly,  this breaks things because the checkPermissons method is checking if it's greater than, not greater than or equal to?

**Comment by robot-rover** [comment]
Hi, if the bot is making its own role then how do you excpect it to move its own role to the top of the hierarchy. You would have to do that yourself

**Comment by robot-rover** [comment]
The way Discord perms work you cannot move your own highest perm or change it, nor can you make a new perm above your highest perm. This is why You are getting the error if I understand what you are trying to do

**Comment by SamboyCoding** [comment]
Then why have the function to create a role, and why have an example which does exactly this?

**Comment by SamboyCoding** [comment]
I'm trying to make a perm BELOW mine, and it is, but it's not letting me set it's name, color, or anything, saying I don't have permission because it's above me when it's not.

**Comment by theIglooo** [comment]
I'll look into this once I'm out of class if no one else does (~4 hours)

**Comment by SamboyCoding** [comment]
Any news on that @theIglooo?

**Comment by theIglooo** [comment]
I ended up being busy and still am, I _should_ be open tomorrow or late tonight

**Comment by SamboyCoding** [comment]
Right, I've got more info. When you create a rank, it doesn't update the current rank's position (that of the bot) so the rank is created below the bot's rank, and appears to have the exact same position as the current one, causing the permission check to fail.

**Comment by SamboyCoding** [comment]
Hmm... i'm now in a server with loads of roles, and it works fine! It seems to only happen with servers with 0-2 roles. More testing required.

**Comment by theIglooo** [comment]
Looks like a Discord bug, everything below was done without Discord4J.

I deleted some roles and then checked the role list which has the positions 0, 1, 4(should be 2) and 5(should be 3)
[The list after deleting](https://u.pomf.is/tyrxxp.png)
[Adding roles puts them on 1 and doesn't adjust the rest of the list](https://u.pomf.is/hydzzb.png)

[Moving a role will change the positions to the correct value](https://u.pomf.is/unsenl.png)
[but it also kinda screws the role list (at least in the client)](https://u.pomf.is/gdpsfd.webm)

**Comment by SamboyCoding** [comment]
Fair enough... where's the discord issue tracker?

**Comment by SamboyCoding** [comment]
Alright. I've filed an issue with discord. Thanks for your time @theIglooo!

**Comment by SamboyCoding** [comment]
![image](https://cloud.githubusercontent.com/assets/7011721/20007630/0342149a-a295-11e6-94fc-efe9042252ff.png)
Right. I posted on the Discord Dev #bugs channel, and got this response. Looks like someone's gonna need to fix this on this end, @theIglooo

**Comment by SamboyCoding** [comment]
Ignore the commit added above. Those changes have been rescinded.

**Comment by SamboyCoding** [comment]
Nice!
