### ISSUE TITLE
Reconnecting is brutal on the CPU

### ISSUE THREAD

**Issue by darkhax** [austinv11/Discord4J#162]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Recently noticed that when my bot was trying to reconnect, it's CPU usage went up significantly. Almost maxed out my i7-6700hq. 

### Steps to Reproduce
1. Turn a bot,
2. Do something to disconnect it from Discord's servers. In my case it was closing the lid on a laptop, which put the PC to sleep.
3. Monitor CPU usage for increased usage. **NOTE** Due to the performance impact of a high CPU usage program, it may be best to have whatever you use to monitor opened up first.

...

**Expected behavior:**
Reconnection attempt would be made without causing large increase in CPU usage.

**Actual behavior:**
The CPU usage went up drastically, and the console spammed many exceptions. 

**Stacktrace (if applicable):**
https://gist.github.com/darkhax/9a730ddaa17bc2fd069c3f3fe5758555

**Version affected:**
2.6.1

### Additional Information
In this situation, my bot does not have any additional code for handling reconnection. Bot source can be found [here](https://github.com/darkhax/Euclid). I have had issues reproducing the issue since first experiencing it, however I definitely have been able to reproduce it.

**Comment by GrandPanda** [comment]
Reconnects (and a lot of other internal behaviors of the library) have been reworked on the `websocket-rewrite` branch. Would you mind testing the behavior of reconnects on that branch? You can get it by using the version `websocket-rewrite-SNAPSHOT` or `42fb214` in maven/gradle.

**Comment by darkhax** [comment]
Thanks for the suggestion. I have not been able to reproduce with the newer snapshot.

**Comment by Jikoo** [comment]
I was having issues with reconnection as well - Discord4J was consuming more and more memory with each reconnect, eventually leading to it running out of memory and crashing, so I swapped to `websocket-rewrite-SNAPSHOT`. Unfortunately, the first reconnection attempt resulted in an alternating `UpgradeException` and `IllegalStateException`. Eventually, the erroring repeated reconnection attempts caused the CPU usage to go through the roof.

http://pastebin.com/2mWKZKdi

**Comment by GrandPanda** [comment]
Those logs did not come from `websocket-rewrite`.

**Comment by Jikoo** [comment]
Odd. I upgraded to it last night - it's possible I managed to retrieve a cached version of the file I uploaded, I suppose. I'll recompile, reupload, and restart. Thanks!
