### ISSUE TITLE
Application crash while looking for module in JDBC library

### ISSUE THREAD

**Issue by TaylerNest** [austinv11/Discord4J#165]
### Description
When Discord4J tries to load JDBC class (in my case - Xerial's JDBC), Class.forName() causes triggered actions inside this class BEFORE declaration of another required classes (? not sure what's actually going on inside JDBC class), so we have exception like this: http://pastebin.com/Dnr7a3p9
In fact, this can happen with ANY another class in another libraries that has static { } blocks under certain circumstances. So, basicly, the simplest and the best solution avaible is to remove static module loading from Discord4J, Class.forName() is really bad. This occurs at sx.blah.discord.modules.ModuleLoader.loadExternalModules(ModuleLoader.java:223), as you can see from exception higher.

### Steps to Reproduce
1. Create Discord4J module
2. Add class that uses static {} blocks in way it uses libraries like xerial's JDBC (or add library like it)
3. Profit, you're crashed forever!

...

**Expected behavior:** module successfully loaded and everything works well

**Actual behavior:** Class.forName() used to load class breaks everything

**Stacktrace (if applicable):** http://pastebin.com/Dnr7a3p9

**Version affected:** 2.6.1

P.S. Sorry for my english if it is bad :(

**Comment by TaylerNest** [comment]
[Referenced](https://bitbucket.org/xerial/sqlite-jdbc/issues/218/classforname-loading-disadvantage) this in Xerial's JDBC repo as well

**Comment by ArsenArsen** [comment]
I think this is only supposed to skip to the next module, but I don't see how this could be because of D4J. I'll test it.

**Comment by TaylerNest** [comment]
As i said, when Class#forName called for one of classes inside module jar, it executes static blocks. Actually this is fault of both D4J AND JDBC. And as I referenced, i have created an issue on Xerial's repo, but I think Discord4J SHOULD predict such kind of problems due to using static blocks in some well-known libraries.

**Comment by GrandPanda** [comment]
Created a module with the linked sql library shaded into the jar and it loaded just fine. Not sure what your issue is.

**Comment by TaylerNest** [comment]
I'll try it again today.

**Comment by ArsenArsen** [comment]
Ok, I have been watching over this thread and I've gotta say how many wrong things I have found.

1. JDBC is not a library, its a java internal binding system for relational database drivers.
2. Xerial's SQLite library works flawlessly on all OS' I use so I do not think its them.
3. You probably just failed to shade everything in. Post your JAR and/or sources.

I agree on, the part where Discord4J should ignore the modules that failed to load, though.

**Comment by TaylerNest** [comment]
Tried by myself
https://github.com/TaylerNest/d4j-sqlite-temp
Still not working.

**Comment by GrandPanda** [comment]
I feel like I must be missing something. A `ClassNotFoundException` is thrown [here](https://github.com/TaylerNest/d4j-sqlite-temp/blob/master/src/main/java/com/taylernest/sqlite/SQLite.java#L22) because there is no such class as `org.xerial.SQLite`. If you change it to a class that actually exists in [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc), it works just fine.

**Comment by ArsenArsen** [comment]
This one is not our fault. As Panda stated your'e initializing the wrong class. Plus there is no need to do that, JDBC does it for you. Remove that line and try-catch.

**Comment by ArsenArsen** [comment]
I am actually able to reproduce this @GrandPanda ..

It is on a linux machine loading the jar that he has. Looks to me personally like a Java hiccup, I've hacked together a workaround for it. Will PR now.

**Comment by TaylerNest** [comment]
Same thing on my Windows 10
Also, fixed error in my repo, thanks - i've been busy today and made this mistake. But this doesn't solves the problem - enable method is never executed, crash happens BEFORE enabling modules - as i said, on classes scanning Class.forName() is executed for each class in jar, but it triggers static { } blocks execution.
But how to fix it - i don't actually even imagine, it seems unsolvable due to static module loading. No offence.

**Comment by TaylerNest** [comment]
If this isn't goes to be fixed, it will be better to notify module developers that they may need to link dependencies using alternative ways (maybe dynamic loading) and put them into subfolder or inside jar as is if they want to really avoid such kind of errors.

**Comment by ArsenArsen** [comment]
It can be temporarly resolved, but there is absolutely zero need for such thing.  Try to update sqlite and remove the static block. @GrandPanda did it successfully after all, meaning its a problem on your end(s?).

**Comment by TaylerNest** [comment]
But as I know, it seems like @GrandPanda used github repo - is it official now? How it differs with bitbucket repo, are they just moved to github?

**Comment by ArsenArsen** [comment]
@TaylerNest Does not matter, just shade it in.

**Comment by GrandPanda** [comment]
Yeah, just tried it again to make sure I'm not crazy. It works perfectly fine. I've attached the built module jar which produces this output: http://hastebin.com/agazebehus.md

[moduletest.zip](https://github.com/austinv11/Discord4J/files/652873/moduletest.zip)

**Comment by TaylerNest** [comment]
Now using the newest version of Xerial's SQLite library, and it works. Sorry for my stupidity.
