### ISSUE TITLE
ConcurrentModificationException in GuildCreateEvent

### ISSUE THREAD

**Issue by Masterzach32** [austinv11/Discord4J#166]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
This issue has been happening for almost 2 weeks now, and I have talked about it with @GrandPanda at least twice on the D4J server, but it has not been addressed recently, so I created an issue to try and make this bug known. Basically, my bot logs in with multiple shards and almost 1000 total servers, a ConcurrentModificationException is sometimes thrown, which then fires a chain of more ConcurrentModificationExceptions and NullPointerExceptions, causing every shard to fail to log in. This does not happen every time, so I am uncertain to the cause.

### Steps to Reproduce
1. Log bot in with at least 2 shards
2. Wait for errors to spam console

**Expected behavior:** GuildCreateEvent fires without a problem

**Actual behavior:** GuildCreateEvent throws a ConcurrentModificationException

**Stacktrace (if applicable):** http://hastebin.com/upohenamiw.pl
http://hastebin.com/zarodalipi.pl

**Version affected:** websocket-rewrite-SNAPSHOT

**Comment by GrandPanda** [comment]
Like I said when we talked about it, if it's not consistently reproducible, then there's really not much I can do. You're the only one to ever report this and even you can't get it to consistently happen. If you or anyone else has any more information, please reply here.

**Comment by manuelgu** [comment]
Can confirm this one. First time this happened, randomly for 1 out of about 300 guilds. Cannot reproduce either.
