### ISSUE TITLE
Rare case of concurrency causing SocketException's for DiscordVoiceWS sending thread

### ISSUE THREAD

**Issue by ArsenArsen** [austinv11/Discord4J#169]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Because of the concurrency for audio sending in DiscordVoiceWS there's a rare case when closing the send socket and sending a new 20ms frame matches up

### Steps to Reproduce
1. Be so lucky that upon leaving a packet is sent to a voice channel

**Expected behavior:** Since the socket is closed it will just not send the packet

**Actual behavior:** Packet is still being sent

**Stacktrace (if applicable):** http://hastebin.com/mequgofaku

**Version affected:** websocket-rewrite

**Comment by Blogshot** [comment]
I have reason to believe this error is not fixed. Yesterday i synced gradle the error still occurs in my bot.

Pastebin with a snippet of my source code:
http://pastebin.com/T6Qre7dG
