### ISSUE TITLE
Encountered error on voice websocket: org.eclipse.jetty.io.EofException: null

### ISSUE THREAD

**Issue by Blogshot** [austinv11/Discord4J#171]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
My Bot is joining channels and playing small mp3-files. I implemented a standard TrackFinishedListener which disconnects from the channel after the mp3 has finished. I noticed a steadily increasing usage of RAM and searched for errors in the logfile.
On random occasions the voice channel is left by throwing an error. Is it possible that the mp3-files remain in memory?

### Steps to Reproduce
1. Join voice channel
2. Play audio (creates error)
3. Leave voice channel

**Expected behavior:** [What was supposed to happen]
Clean exit from voice channel.

**Actual behavior:** [What actually happened]
Exiting the voice channel occurs with error.

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]
http://pastebin.com/MnABN8DG

**Version affected:** [The version of Discord4J]
Current snapshot of websocket-rewrite (2.6.1)

### Additional Information
To the users everything seems normal. The bot disconnects after playing the audio. This is not a bot-breaking bug.
The mp3-Files are not currupted, the server fully virtualized. I think we can rule out any hardware-errors.

**Comment by GrandPanda** [comment]
Just to make sure, is your listener actually triggering, the bot leaving, and then the error is thrown or is it that the bot leaves the voice channel as the result of an error thrown when the track finishes? 
Also, could you clarify the affected version? You said `websocket-rewrite` but that is not 2.6.1.

**Comment by Blogshot** [comment]
I am on websocket-rewrite-SNAPSHOT. I just assumed the codebase to be 2.6.1, sorry for that. 

I just updated the bot to log something after triggering the listener to determine if it gets executed correctly. Will report back in a few hours.

**Comment by Blogshot** [comment]
After my last comment i synced gradle to get the latest build and updated my bot.

The error was not thrown again in the last 22 hours, despite being activated nearly 1000 times. However, the RAM usage has grown again. So, even if this error occurs again it is most definitely not the source my growing RAM usage.
