### ISSUE TITLE
IUser Role modifications inconsistent

### ISSUE THREAD

**Issue by FerusGrim** [austinv11/Discord4J#172]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
I've a bot that handles role assignments around 100 times per day, via two different commands.

The consistency with which these modifications are successful is sporadic. I've received no errors or exceptions whatsoever.

### Steps to Reproduce
1. Execute command to assign role

...

**Expected behavior:** Role should have been added

**Actual behavior:** Role is added inconsistently

**Version affected:** `f9ce880:shaded` For convenience: [link](https://github.com/austinv11/Discord4J/tree/f9ce880abbbfaf81a9acf12296f29cb49c7228dc)

### Additional Information
Code is [open source](https://github.com/FerusGrim/FurryBot).

**Comment by theIglooo** [comment]
Could you try to replicate this again on websocket-rewrite?
Versions:
`websocket-rewrite-SNAPSHOT` to get latest commit every time you refresh
or
`f6f90c4` for the most recent commit as of this message, you'll have to change it every time something's pushed so you probably want the other one

**Comment by theIglooo** [comment]
Also, if you're going to be adding a lot of roles back-to-back, you should wrap the addRole in a buffer to avoid hitting ratelimits and make sure that the request goes through when it can.
Example:
```java
RequestBuffer.request(() -> {
  try {
    user.addRole(role);
  } catch (MissingPermissionsException | DiscordException e) {
    e.printStackTrace();
  }
});
```

**Comment by GrandPanda** [comment]
If you're adding a lot of roles, it would be better to use `IGuild#editUserRoles()` as you only have to make one request to Discord rather than multiple addRole() requests.

**Comment by FerusGrim** [comment]
@GrandPanda @theIglooo 

I'll take both of those suggestions and comment back when I have a result. :)

**Comment by FerusGrim** [comment]
Using perhaps a combination of the two, this has been fixed!

Loving the websocket rewrite, btw. :)
