### ISSUE TITLE
Reactions not working with RequestBuffer

### ISSUE THREAD

**Issue by JamesGallicchio** [austinv11/Discord4J#175]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Adding reactions through RequestBuffer does not retry if ratelimited

### Steps to Reproduce
1. Add multiple reactions to a message through RequestBuffer.request() quickly
2. Look at message in discord

**Expected behavior:** Add each reaction supplied

**Actual behavior:** Only the first reaction is added

**Version affected:** websocket-rewrite-SNAPSHOT (most recent build)

### Additional Information
The ratelimit is logged:
17:55:35.408 [Event Dispatch Thread] DEBUG sx.blah.discord.Discord4J - Attempted request rate-limited, queueing retry in 180ms
However, the reactions after the first are not added.

**Comment by GrandPanda** [comment]
Gonna mark this as external issue for the time being as I'm 99% sure this is Discord's fault.

**Comment by austinv11** [comment]
This cannot be replicated as of the 23068a6
