### ISSUE TITLE
First DM sent by unique user not being received

### ISSUE THREAD

**Issue by Yatekko** [austinv11/Discord4J#177]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Bot is unable to receive the very first DM sent to it by any user - every DM after the first is received.  The event does not show up on Eclipse's console.

### Steps to Reproduce
1. Have a way to see each message event, such as Eclipse console or catching MessageReceivedEvent
2. Send a DM to the bot

**Expected behavior:** Bot receives every DM sent to it.

**Actual behavior:** The first DM from each user is never received.

**Stacktrace (if applicable):** N/A

**Version affected:** 2.6.1

### Additional Information
It appears that after a user sends a DM for the first time, every subsequent DM will be received, even if the program running the bot is restarted.

**Comment by ArsenArsen** [comment]
Try with `websocket-rewrite-SNAPSHOT` as your version.

**Comment by Yatekko** [comment]
That seems to have fixed the issue, huh.  Thank you very much!
