### ISSUE TITLE
NPE in ChannelUpdateEvent

### ISSUE THREAD

**Issue by manuelgu** [austinv11/Discord4J#181]
### Prerequisites
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
A NullPointerException is randomly being thrown in the ChannelUpdateEvent.

### Steps to Reproduce
Unable to reproduce, just randomly occurs.

**Expected behavior:** No NPE

**Actual behavior:** NPE thrown

**Stacktrace (if applicable):** https://hastebin.com/lorayuladi.pl

**Version affected:** 2.7.0

**Comment by manuelgu** [comment]
Seeing more and more users getting this issue. Any clue?

**Comment by manuelgu** [comment]
Heads up, this wasn't happening with 2.6.1 apparently.

**Comment by manuelgu** [comment]
https://hastebin.com/nequjetuta.swift

This one seems to be related. Happens during startup every so often with the following setup:

`@everyone` has both Send & Read Messages
Channel `#a` has normal permissions for `@everyone` and my bot user has both Read & Send Messages
Channel `#b` has normal permissions for `@everyone` and my bot user has Send Messages negated
Channel `#c` is a clon of `#b` with the exact same setup

**Comment by austinv11** [comment]
This *might* be fixed via 04ee66f
