### ISSUE TITLE
ClosedChannelException right before reconnect

### ISSUE THREAD

**Issue by manuelgu** [austinv11/Discord4J#182]
### Prerequisites
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
A ClosedChannelException is randomly being thrown right before reconnect to WS.

### Steps to Reproduce
Unable to reproduce, just randomly happens.

**Expected behavior:** Reconnect fine without exception

**Actual behavior:** Exception right before it's reconnecting

**Stacktrace (if applicable):** https://hastebin.com/zuyezanuvo.lua

**Version affected:** 2.7.0

**Comment by GrandPanda** [comment]
It's reconnecting *because* of that exception. The reconnect happens afterwards because the channel was closed.

**Comment by GrandPanda** [comment]
That's not D4J's fault. If the channel was closed, there's nothing we can do. It's an exception just like any other, I'm not going to hide it from you.
