### ISSUE TITLE
OGG-Files not supported despite documentation

### ISSUE THREAD

**Issue by Blogshot** [austinv11/Discord4J#185]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Feeding Audioplayer with OGG-Files causes "UnsupportedAudioFileException". Documentation states OGG as supported.

### Steps to Reproduce
    AudioPlayer player = AudioPlayer.getAudioPlayerForGuild(voiceChannel.getGuild());
              
    // feed the player with audio
    player.queue(new URL("https://upload.wikimedia.org/wikipedia/en/4/45/ACDC_-_Back_In_Black-sample.ogg"));

**Expected behavior:**
OGG-Files play as expected.

**Actual behavior:**
UnsupportedAudioFileException is thrown.

**Stacktrace (if applicable):**
http://pastebin.com/cD9kRv0B

**Version affected:**
Websocket-Rewrite

### Additional Information
Quote from https://github.com/austinv11/Discord4J/blob/323f5864b89af14ab17c68ca78bd5d714fb9926f/src/main/java/sx/blah/discord/util/audio/AudioPlayer.java:

	/**
	 * This queues a url for the AudioPlayer.
	 * <br>Supports: ogg, mp3, flac, wav
	 *
	 * [...]
	 */
	public Track queue(URL url) throws IOException, UnsupportedAudioFileException {
		Track track = new Track(new URLProvider(url));
		track.getMetadata().put("url", url);
		queue(track);
		return track;
	}

After some googling, Java itself doesn't seem to support ogg. Every solution relies on third-party libraries.

**Comment by chrislo27** [comment]
Have you tried other ogg format files? For example, downloading the Wikimedia resource and queuing it locally, or trying other ogg files?

**Comment by Blogshot** [comment]
Tested it. The same exception occurs. The ogg-file can't be played, other mp3s in the same folder work.

Pastebin from locally loaded file (no changes to original pastebin though):
http://pastebin.com/ZDxZxPJ0

**Comment by ArsenArsen** [comment]
This documentation is off, should say something like
```java
/**
 * This queues a url for the AudioPlayer.
 * <br>Supports all formats {@link javax.sound.sampled.AudioSystem} does.
 *
 * [...]
 */
public Track queue(URL url) throws IOException, UnsupportedAudioFileException {
	Track track = new Track(new URLProvider(url));
	track.getMetadata().put("url", url);
	queue(track);
	return track;
}```
It clearly shows what the error cause might be.
