### ISSUE TITLE
Message-objects are kept in memory, leading to high memory usage

### ISSUE THREAD

**Issue by Blogshot** [austinv11/Discord4J#186]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I can observe a growing RAM-usage of my bot with ~370 guilds. After a fresh start it takes up circa 270-300 MB. After a short time this grows significantly: After 1 day and 6 hours the RAM-usage is already at 420 MB. When the bot had only 20-50 guilds it took way longer for the memory to be used up so much.

Multiple heapdumps have shown massive amounts of Message-Objects being in memory. I created code to further test this (http://pastebin.com/sSmrAEVv):
1. Looked at the memory shortly after starting the bot (bot had posted 149 messages already)
2. Let the bot post another 100 text-messages
3. Looked at the memory again

The bot had kept every message-object that was written (by any user) in memory: http://imgur.com/a/uOvCG

To me it seems that Discord4J keeps posted messages in memory, therefore letting the memory-usage grow umlimitedly.

### Steps to Reproduce
1. Debug code from http://pastebin.com/sSmrAEVv (parameters: --debug --token=\<token\>)
2. View count of objects on start and after a period of time, ideally after a few dozen message were sent

**Expected behavior:**
Discord4J does not keep messages in memory.

**Actual behavior:**
Messages are stored in memory, leading to increasing memory usage.

**Version affected:**
2.7.0

### Additional Information
Snippet of source used to rebuild the behaviour:
http://pastebin.com/sSmrAEVv

Screenshots of objects in memory after 100 messages:
http://imgur.com/a/uOvCG

**Comment by austinv11** [comment]
Fixed via: https://github.com/austinv11/Discord4J/commit/a970bc9fe0b14eabb46149a2f46c2279a2d3410d

**Comment by Blogshot** [comment]
Synced gradle to deb-SNAPSHOT and did a quick test. Sadly your fix has no effect for me.

Code:
```
// rate limit
int limit = 1010;

while (true) {
    if (client.getGuilds().size() > 0) {   
        try {
            // reduce spamming if below produces errors
            Thread.sleep(limit);
  
            // Enable HIGH-efficiency (...at every iteration, meh..)
            for (IChannel channel : client.getChannels()) {
                channel.getMessages().setEfficiency(MessageList.EfficiencyLevel.HIGH);
            }
                
            // build message to observer RAM-changes
            new MessageBuilder(client)
                .withChannel(client.getGuilds().get(0).getChannels().get(0))
                .withContent("Test-Message")
                .build();
                
            // garbage collect to exclude objects that will be cleaned sometime
            System.gc();
                
        } catch (RateLimitException e) {
            limit += 500;
        } catch (MissingPermissionsException | DiscordException | InterruptedException ignored) {}
    }
}
```

New screenshot of memory:
http://imgur.com/a/FnSG7

There are 344 messages in memory despite setting efficiency to HIGH (no caching whatsoever). Did I set the efficiency wrong?

**Comment by GrandPanda** [comment]
Efficiency should be set before logging in the client.

**Comment by Blogshot** [comment]
I'm using a different token to not disturb the regular action of my production-bot.

Then, how to set efficiency at startup? The only function to do this seems to be in MessageList-objects, which can only be accessed when the client is already connected to the guild. Am I missing something obvious?

**Comment by GrandPanda** [comment]
There's a static method that takes the client you want to set it for. `MessageList.setEfficiency(client, MessageList.EfficiencyLevel.HIGH)` before login should do it.

**Comment by Blogshot** [comment]
That did the trick! will update my production-bot now., thanks!
