### ISSUE TITLE
Blocking on .get() using RequestBuffer

### ISSUE THREAD

**Issue by Paul776** [austinv11/Discord4J#187]
#Hi,

I was looking for a RateLimiter handler and I stumble on your RequestBuffer which seems to be pretty neat. 
At first look it seems that this utility class is just to handle request which don't need a return value

Is there any plan to make this class such as, as long as the request didn't return 200 the future.get() blocks?

Thanks!

**Comment by chrislo27** [comment]
Your question is a bit hard to understand. I can see that you want it to continue instead of on a 429, but on any-200 (or 2XX) status code (I think).
If you look at this line in `RequestBuffer` https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/util/RequestBuffer.java#L228, you'll see that it relies on a `RateLimitException` to occur to initiate the try again. There is no status code handling, and all of that is done in the `Requests` class.

However, I could also see your question as "why doesn't `IRequest#get` block?". To which I can answer - I don't know, and it really should block.

If you'd like to continue talking to us, [our official server](https://discord.gg/NxGAeCY) is a better place rather than GitHub comments.

**Comment by Paul776** [comment]
Thank you for the fix! I have added a small question / comment fr the get with timeout

**Comment by Paul776** [comment]
Unrelated to this but while testing I saw this block

```
				requests.put(future.getBucket(), new CopyOnWriteArrayList<>());
				requestTimer.schedule(new RequestTimerTask(future.getBucket()), future.getDelay(TimeUnit.MILLISECONDS));
			
```

being executed twice for the same "method"

**Comment by Paul776** [comment]
An other one a bit more critical, more or less heavy

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                          at xxxxx.RequestBuffer$RequestTimerTask.run(RequestBuffer.java:290)
```

line 290 is this one in the TimeTask's run Method:
for (RequestFuture future : futures) {

**Comment by Paul776** [comment]
An other thing as well:

```
if (futuresToRetry.size() > 0 && futuresToRetry.get(0).getDelay(TimeUnit.MILLISECONDS) > 0) {
          requests.replace(bucket, futuresToRetry);
          synchronized (requestTimer) {
            requestTimer.schedule(new RequestTimerTask(bucket), futuresToRetry.get(0).getDelay(TimeUnit.MILLISECONDS));
          }
```

What happens if getDelay() returns lets say 0.00001  and at the moment of reaching requestTimer.schedule getDelay() actually returning a negative value?
requestTimer.schedule will fail and the bucket will be lust forever?

**Comment by austinv11** [comment]
You are gonna need to elaborate on https://github.com/austinv11/Discord4J/issues/187#issuecomment-269627900

**Comment by Paul776** [comment]
@austinv11 
```
 if (!requests.containsKey(future.getBucket())) {
        requests.put(future.getBucket(), new CopyOnWriteArrayList<RequestFuture>());
        requestTimer.schedule(new RequestTimerTask(future.getBucket()), future.getDelay(TimeUnit.MILLISECONDS));
      }
```

Apparently during my heavy load testing this condition 
`requests.containsKey(future.getBucket())` is flowed because if a T1 do the check and reach  requests.put but not yet execute it and a T2 comes the check will pass for it too

**Comment by Paul776** [comment]
Something else I noticed as well and that could eventually cause a NPE.

```
 if (!future.isDone()) {
      if (!requests.containsKey(future.getBucket())) {
        requests.put(future.getBucket(), new CopyOnWriteArrayList<RequestFuture>());
        requestTimer.schedule(new RequestTimerTask(future.getBucket()), future.getDelay(TimeUnit.MILLISECONDS));
      }

      //TODO here there can be NPE because the bucket could be remove by the TimerTask
      requests.get(future.getBucket()).add(future);
    }
```

Imagine there is already a bucket called "SendMessage" and there is already a TomerTask running trying the re-execute the requests. 
Now let's say there is a new  T1 that comes an try to execute the requests and that it actually gets 429 and BEFORE it actually reaches this line
`requests.get(future.getBucket()).add(future);`
Imagine the TomerTask has completed and it actually managed to get 200 to ALL its list of futures so in the TimerTask this line will be reached
` requests.remove(bucket);`
Now back to T1 that will execute this
`requests.get(future.getBucket()).add(future);`

You gonna get a NPE because the bucket 'at  that point' doesn't exist anymore

**Comment by Paul776** [comment]
@austinv11 
Thank you for fixing these issues.

I have been running the latests code against some heavy rate-limited and there is 'a scenario' where it looks like the bucket gets deleted with requests that have not yet been completed (basically the bucket is wiped) and I endup with multiple future stuck on .get() indefinitetly

I'm trying to debug by adding some log message but I can tell you for sure that the requests map is empty even though there is still futures waiting on the .get()

**Comment by ArsenArsen** [comment]
@Paul776 I am pretty sure this is patched in the latest commit. Not completely sure. Try to update.

**Comment by Paul776** [comment]
@ArsenArsen Uuuh yes indeed I didn't see the latest commit! I will try now

**Comment by Paul776** [comment]
@austinv11 
An other small bug I just noticed. When I call killAllRequests the requests map is not cleaned up o I still have loads of futures waiting on the .get() (shutting down the executor service doesn't trigger the latch's InterruptException

**Comment by austinv11** [comment]
Oops, I'll get on that. There is also a weird chance that requests will be out of order that I'm working to resolve too.

**Comment by Paul776** [comment]
Ah yes.. also with the latest commit it looks like concurrency got a serious hit (because of the 
requestService.get().execute(new Runnable() {) each requests are process one by one (and indeed maybe in different order they are coming)

**Comment by austinv11** [comment]
RequestBuffer requests should now be more consistent as of 23068a62ae45bf3a95296fb61914390a48147ce8
