### ISSUE TITLE
MemoryLeak, AudioInputStreams not closed correctly

### ISSUE THREAD

**Issue by Blogshot** [austinv11/Discord4J#191]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
After invoking 'Audioplayer.queue(inputStream)' the instances of InputStream are not closed correctly afterwards. This results in bloated instances as well as permanently growing memory-usage. This issue is especially significant for audio-heavy bots.

### Steps to Reproduce
Queue an inputstream (or any other valid object) into the audioplayer. 

```
public void playAudio(IVoiceChannel voiceChannel, IChannel textChannel, URL soundFile) {
    try {

      // Join channel
      voiceChannel.join();

      // get instance of audio player      
      AudioPlayer player = AudioPlayer.getAudioPlayerForGuild(voiceChannel.getGuild());

      // feed the player with audio
      player.queue(soundFile);

    } catch (MissingPermissionsException e) {
      // feedback with helpful information
      writeMessage(textChannel, "I have no permission to join this channel.");
    } catch (UnsupportedAudioFileException | IOException e) {
      e.printStackTrace();
    }
}
```

**Expected behavior:**
AudioInputStream-instances are closed.

**Actual behavior:**
AudioInputStream-instances are being kept in memory. (See screenshot)

**Stacktrace (if applicable):**
Logging is set to INFO, no exceptions are being thrown.
The only thing strange being logged is 
`[HttpClient@XXXXXXXXXX-XXX] INFO sx.blah.discord.Discord4J - Voice Websocket disconnected with status code 1000 and reason "null"`
Might be unrelated.

**Version affected:**
dev-SNAPSHOT, last synced: 03.01.16

### Additional Information
Screenshot of memory dump (Notice "AmplitudeAudioInputStream"):
http://imgur.com/a/Dk2Kx

The audio files are ~20-80 KB size, each no longer than 6 seconds.

**Comment by ArsenArsen** [comment]
Why not just use lavaplayer? I even made a simple implementation, called lavaplayerbridge, for anyone to use.

**Comment by MatrixTunnel** [comment]
Even though I agree with you @ArsenArsen, some people just want to use the built in way.

**Comment by Blogshot** [comment]
I think I will try LavaPlayer tomorrow, thanks for the hint. ;)

Nonetheless I think the built-in player should be free of critical bugs. Even if I decide to use another player I think this bug is worth fixing.

**Comment by ArsenArsen** [comment]
I agree.. All bugs should be smashed.

**Comment by Blogshot** [comment]
Addition:
I added a manual `player.clean();` in TrackFinishedListener.

```
public class TrackFinishedListener implements IListener<TrackFinishEvent> {

  @Override
  public void handle(TrackFinishEvent event) {
    // Clean memory manually to counteract memory leak
    event.getPlayer().clean();
  }

}
```

The bot has used around  ~367 MB memory for the last 4 hours despite being active in >900 guilds and being activated nearly 1000 times. Current heapdumps show that there are only 9 instances of AudioPlayer at the moment, which is a realistic number and implies that garbage-collection has successfully removed unused instances. I will further observe this, but the issue might be resolved.

## Results of further investigation:
I found that AudioPlayer.java contains a static field (`private final static Map<IGuild, AudioPlayer> playerInstances`) that saves all created instances of AudioPlayer to reuse them when using `AudioPlayer.getAudioPlayerForGuild(guild);`.

Because queued tracks are not cleaned up anywhere\*, they are being kept in memory because `playerInstances` still references them.

\* Track.close(): 
```
protected void close() {
  if (stream != null && provider.isReady())
    try {
      stream.close();
    } catch (IOException e) {
      Discord4J.LOGGER.error(LogMarkers.VOICE, "Discord4J Internal Exception", e);
    }
}
```
This closes the stream, but keeps the content of it inside `private final AmplitudeAudioInputStream stream;` (as far as I understand it, closing InputStream just releases the file handle in the kernel and does not free the used memory.)
This behaviour seems to explain all symptoms I experienced. 

## Possible fix
Since my manual workaround just cleans the trackQueue it should be sufficient to additionally  remove the instance of `Track` from `trackQueue` after Track.close():
```
public Track skip() {
  if (trackQueue.size() > 0) {
    Track track = trackQueue.remove(0);
    
    if (track.isReady() && track.getCurrentTrackTime() == track.getTotalTrackTime()) { //The track was actually skipped, not skipped due to the way my logic works
      client.getDispatcher().dispatch(new TrackSkipEvent(this, track));
    }

    if (isLooping()) {
      track.rewindTo(0); //Have to reset the audio
      trackQueue.add(track);
    } else {
      track.close();

      /*
         possible fix: remove Track from trackqueue to enable it for garbage collection
      */
      trackQueue.remove(track);
    }
    return track;
  }
  return null;
}
```

I hope my research proves correct and will help to solve this. I will have to wait for a bit to see if my workaround actually kills this issue. (I sure hope so, otherwise this wall of text will have been a huge waste of time :D)


Side note; most likely unrelated:
`java.net.SocketException: Socket is closed` has not appeared again since this change. (This exception was thrown regularly before my workaround.)

**Comment by austinv11** [comment]
@Blogshot I'm not sure how that would fix it because you are removing an already removed track because we get the track object by actually removing it in the beginning of the method via `Track track = trackQueue.remove(0);`

**Comment by Blogshot** [comment]
@austinv11 ah, you're right.

Then somewhere else must be some kind of reference to the track. I don't have in-depth experience with Discord4J, but will try to find useful clues.

**Comment by austinv11** [comment]
Closing this for now since a lot has changed, feel free to reopen if this is still an issue
