### ISSUE TITLE
dependency jflac 1.3 is no longer hostet on jitpack (newer version 1.5 is)

### ISSUE THREAD

**Issue by nilsmahlstaedt** [austinv11/Discord4J#193]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Buildng Discord4J with sbt is not possible, as it can't find the dependency ` jflac:jflac:1.3` on jitpack

### Steps to Reproduce
1. Build project with `Discord4J (Version 2.7.0) as dependency`

**Actual behavior:** 
```
::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: jflac#jflac;1.3: not found
[warn]  :: org.tritonus#tritonus-dsp;0.3.6: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          jflac:jflac:1.3
[warn]            +- com.github.austinv11:Discord4j:2.7.0 (C:\projects\scala\music-snake\build.sbt#L35-42)

```

**Version affected: 2.7.0**

**Comment by quanticc** [comment]
Could you give us more info about the resolvers in your build.sbt file?

Seems like you're missing the jcenter one. http://www.scala-sbt.org/1.0/docs/Resolvers.html

**Comment by nilsmahlstaedt** [comment]
```
 "releases" at "https://oss.sonatype.org/content/repositories/releases",
  "Typesafe Releases" at "https://dl.bintray.com/typesafe/maven-releases/",
"jitpack" at "https://jitpack.io"
```

**Comment by austinv11** [comment]
You are gonna need to add the jcenter repo too at: http://jcenter.bintray.com
