### ISSUE TITLE
Threads still running after logout

### ISSUE THREAD

**Issue by Sadillac** [austinv11/Discord4J#194]
### Prerequisites
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
After IDiscordClient#logout() the bot leaves threads alive not allowing the main thread to terminate.

### Steps to Reproduce
1. Startup bot
2. IDiscordClient#logout() - in my case in reaction of a received message

**Expected behavior:** Terminating main thread.

**Actual behavior:** Threads still running, see image in additional information.

**Stacktrace (if applicable):** -

**Version affected:** 1bf774c

### Additional Information
These are the running threads after the logout:
![image](https://cloud.githubusercontent.com/assets/5767967/21850399/ba3a566c-d80a-11e6-8067-dec8c41b7866.png)

**Comment by austinv11** [comment]
Fixed via 61f2300
