### ISSUE TITLE
failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by TheFjonG** [austinv11/Discord4J#20]
### Prerequisites

* [ ] This issue specifically has something to do with Discord4J

### Description
My bot is failing to load class "org.slf4j.impl.StaticLoggerBinder".
I used Gradle to get Discord4J and got all the dependencies.

Im aware that Slf4j.Simple should be downloaded through Gradle. But it isnt.
Im using commit: 7a0b1fb.

### A way to fix it
Get Slf4j-nop-1.7.9 through Gradle / Maven.

`repositories {
       ...  
	maven {
		url "http://repo2.maven.org/maven2/";
	}
}`

`dependencies {
   ...
   compile "org.slf4j:slf4j-simple:1.7.9";
}
`

#Additional information

> As of SLF4J version 1.6, in the absence of a binding, SLF4J will default to a no-operation (NOP) logger implementation. 
You can download SLF4J bindings from the project [download link](http://www.slf4j.org/download.html)

Source: http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by phantamanta44** [comment]
You need to add an SLF4J implementation as a dependency. Try using [logback](http://logback.qos.ch/).

**Comment by austinv11** [comment]
This is intentional behavior on the part of slf4j.
