### ISSUE TITLE
Refactod RequestBuffer doesn't block anymore on .get()

### ISSUE THREAD

**Issue by Paul776** [austinv11/Discord4J#203]
Hello,

@austinv11 
I just checked out the new RequestBuffer refactored into using an internal Callable. But because of this and the fact that the Callable returns "null" when there request is rate-limitted the future.get() 'never' blocks.. and always returns null

**Comment by chrislo27** [comment]
You went out of your way to delete the issue template instead of filling it out - now I have to ask what commit, what do you mean by "refactored" (because it wasn't restored refactored, but _rewritten_).

What do you mean by "internal Callable"? RequestBuffer uses a Future, as it has `get` compared to Callable's `call`.

**Comment by Paul776** [comment]
Sorry I don't know which commit it was. I tested on the latest 'dev branch' version.

This is new, before it was not a Callable but custom Future

`private static class RequestCallable <T> implements Callable<T> {`

And because of this:

```
public T call() throws Exception {
        try {
          if (!firstAttempt)
            request.onRetry(future);

          if (!future.isCancelled()) {
            T value = request.request();
            timeForNextRequest = -1;
            successful = true;
            return value;
          }
        } catch (RateLimitException e) {
          firstAttempt = false;
          timeForNextRequest = System.currentTimeMillis()+e.getRetryDelay();
          bucket = e.getMethod();
        }

        return null;
      }
```
when a request is actually rate-limitted it goes to the 'return null'

So client side when We do:

```
RequestBufferr.RequestFuture<MyClass> future = RequestBuffer.request(.....)
future.get() 
```

the future.get() return null instead of blocking until the request goes through

**Comment by austinv11** [comment]
This should be fixed on the latest dev
