### ISSUE TITLE
Kick Option

### ISSUE THREAD

**Issue by SaubereSacheLP** [austinv11/Discord4J#208]
Hi, could you please add a kick/ban feature?
I searched for a while and didnt found it, would be nice!
~SaubereSache

**Comment by ArsenArsen** [comment]
It exists.

IGuild#banUser(IUser)
IGuild#kickUser(IUser)

Or something similar.

**Comment by chrislo27** [comment]
`IGuild#banUser`
`IGuild#kickUser`

We have a Discord server - asking questions like these is recommended there instead.

**Comment by GrandPanda** [comment]
`IGuild#kickUser()` and `IGuild#banUser()`
