### ISSUE TITLE
Cannot login using ClientBuilder

### ISSUE THREAD

**Issue by decyg** [austinv11/Discord4J#21]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
On attempting to login with following code
```
ClientBuilder builder = new ClientBuilder();
builder.withToken("mytoken");
IDiscordClient client = builder.login();
```
where mytoken is my account token it gives me a java.lang.NoSuchFieldError on version 2.4.0

### Steps to Reproduce
1. Run above code using 2.4.0 in a new project

...

**Expected behavior:**
Login and allow me to access the client 

**Actual behavior:** 
Exception thrown, program does not start

**Stacktrace (if applicable):**
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955)
	at sx.blah.discord.api.internal.Requests.<clinit>(Requests.java:53)
	at sx.blah.discord.api.internal.DiscordClientImpl.validateToken(DiscordClientImpl.java:231)
	at sx.blah.discord.api.internal.DiscordClientImpl.login(DiscordClientImpl.java:217)
	at sx.blah.discord.api.ClientBuilder.login(ClientBuilder.java:104)
	at BaseBot.login(BaseBot.java:33)
	at BaseBot.main(BaseBot.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
Please note that even though it's calling the methods in BaseBot, there is nothing in that java file other than the code mentioned above in the main method

**Version affected:** [The version of Discord4J]
2.4.0

### Additional Information

I don't know if this issue is just me being an idiot or what but any help would be greatly appreciated

**Comment by iabarca** [comment]
What kind of dependency management are you using? It seems you're using a different version of httpclient

**Comment by decyg** [comment]
I just added the listed repository and dependency to my pom.xml file and
enabled auto importing in intellij to let it grab all dependencies, I might
have conflicting dependencies from my main project now you mention it, will
check tomorrow and get back to you ASAP thanks.

**Comment by austinv11** [comment]
Can you try using version 2.4.2?

**Comment by decyg** [comment]
Yeah using 2.4.2 made no difference but i removed the other maven dependencies i had and that worked. I completetly forgot what maven dependencies i actually had but i removed:
com.github.taksan:skype-java-api:1.4
org.apache.commons.codec/lang/logging
org.apache.http.*
org.jdom2.*
com.google.api/common/thirdparty

Sorry i couldn't be more helpful, i should have had my project on version control or kept a note of what i was removing before i did it

**Comment by austinv11** [comment]
It appears to be a conflict with the apache http client versions. What version were you using?

**Comment by decyg** [comment]
I'm really sorry but i can't remember, i removed the maven repos i was using through intellij without noting them down

**Comment by austinv11** [comment]
I'm going to close this for now. But you can see the versions of httpcomponents Discord4J uses here: https://github.com/austinv11/Discord4J/blob/master/pom.xml#L43-L59. I would recommend trying to use those versions only.
