### ISSUE TITLE
NPE On "RequestBuffer"

### ISSUE THREAD

**Issue by xaanit** [austinv11/Discord4J#215]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already [NOTE: [This](https://github.com/austinv11/Discord4J/issues/203) seems to be an issue somewhat similar, but I was asked to make this by Austin]

### Description
Request Buffer is throwing an NPE on line 39 of it's class. 

### Steps to Reproduce
Unsure, the source (outside of it was a RequestBuffer) was never reported to me in the stacktrace.

...

**Expected behavior:** Send a string or an EmbedObject to a specified channel

**Actual behavior:** NPE

**Stacktrace (if applicable):** [NPE Stacktrace](http://pastebin.com/HfJRMhSm), [Latest request coded before the NPE hit, should have been uncalled anyway](http://pastebin.com/NJauqcfM), [Read Time out, right before the NPE](http://pastebin.com/YQZzUG2A)

**Version affected:** dev-SNAPSHOT

### Additional Information
The last request should have been uncalled, but I wanted to include it anyway since it's the only time I'm doing multiple rate limitable situations. To quote quantic:
quantic - Today at 12:03 AM
I visualize an scenario where the first sendMessage is called twice after being rate limited when calling the second sendMessage

Eclipse never reported exactly where I was calling the request buffer from so I have no way of knowing exactly where the error came from (And provide the relevant code)

**Comment by theIglooo** [comment]
I'm pretty sure that's the same NPE that was fixed recently, update to latest dev since line 39 is now a blank line.

**Comment by quanticc** [comment]
Still, this reveals an issue with null-checking before synchronized only. The condition might not hold true anymore once a thread acquires that lock.

```java
if (future.getBucket() != null) {
	synchronized (requests) {
		// needs an extra if (future.getBucket() != null) here
...
```

**Comment by xaanit** [comment]
@theIglooo I'm currently transferring all of my sendMessages into a helper method (which calls a buffer before sending the message to the channel)

Regardless that method should *never* have been called. I included it as the timings lined up but...

**Comment by xaanit** [comment]
Was asked to add this: http://pastebin.com/ruLJ5iNH

Not swallowing the exception - I log everything that I can.
