### ISSUE TITLE
Relicense to GNU LGPL 3

### ISSUE THREAD

**Issue by austinv11** [austinv11/Discord4J#218]
The maintainers of this project have decided to relicense D4J from GPL 2 to [LGPL 3](https://choosealicense.com/licenses/lgpl-3.0/) as it is a less restrictive license yet still maintains the openness of the D4J library.

In order to do this we must get written approval from every contributor whose contribution is still present in D4J. If you are a contributor, please comment on this issue stating `I, @mention, approve relicensing Discord4J to LGPL 3`.

Here are the contributors from whom we require approval:
* [x] @austinv11
* [x] @GrandPanda 
* [x] @chrislo27 
* [x] @theIglooo 
* [x] @quanticc 
* [x] @nerd 
* [x] @phantamanta44 
* [x] @ArsenArsen 
* [x] @lclc98 
* [x] @Masterzach32 
* [x] @craftu 
* [x] @robot-rover 
* [x] @Kaioru 
* [x] @manuelgu 
* [x] @poncethecat 
* [x] @langerhans 
* [x] @nija123098 
* [x] @davue 
* [x] @ChrisVega 
* [x] @UnderMybrella 
* [x] @DV8FromTheWorld 
* [x] @BloodShura 
* [x] @arcadeena
* [x] @jammehcow
* [x] @Techtony96 
* [x] @JamesGallicchio

**Comment by austinv11** [comment]
I, @austinv11, approve relicensing Discord4J to LGPL 3.

**Comment by ArsenArsen** [comment]
👍

**Comment by theIglooo** [comment]
I, @theIglooo, approve relicensing Discord4J to LGPL 3.

**Comment by quanticc** [comment]
I, @quanticc, approve relicensing Discord4J to LGPL 3

**Comment by DV8FromTheWorld** [comment]
I, @DV8FromTheWorld, approve relicensing Discord4J to LGPL 3.

**Comment by MinnDevelopment** [comment]
I vouch for this

**Comment by davue** [comment]
I, @davue, approve relicensing Discord4J to LGPL 3.

**Comment by poncethecat** [comment]
I, @poncethecat, approve relicensing Discord4J to LGPL 3.

**Comment by chrislo27** [comment]
I, @chrislo27, approve relicensing Discord4J to LGPL 3.

**Comment by Techtony96** [comment]
I, @Techtony96, approve relicensing Discord4J to LGPL 3.

**Comment by Masterzach32** [comment]
I, @Masterzach32, approve relicensing Discord4J to LGPL 3

**Comment by langerhans** [comment]
I, @langerhans, approve relicensing Discord4J to LGPL 3.

**Comment by GrandPanda** [comment]
I, @GrandPanda, approve relicensing Discord4J to LGPL 3.

**Comment by nija123098** [comment]
I, @nija123098, approve relicensing Discord4J to LGPL 3.

**Comment by jammehcow** [comment]
I, @jammehcow, approve relicensing Discord4J to LGPL 3.

**Comment by nerd** [comment]
I, @nerd, approve relicensing Discord4J to LGPL 3.

**Comment by lclc98** [comment]
I, @lclc98, approve relicensing Discord4J to LGPL 3.

**Comment by Kaioru** [comment]
I, @Kaioru, approve relicensing Discord4J to LGPL 3

**Comment by UnderMybrella** [comment]
I, @UnderMybrella, approve relicensing Discord4J to LGPL 3

**Comment by robot-rover** [comment]
I, @robot-rover , approve relicensing Discord4J to LGPL 3.

**Comment by BloodShura** [comment]
I, @BloodShura, approve relicensing Discord4J to LGPL 3

**Comment by phantamanta44** [comment]
I, @phantamanta44, approve relicensing Discord4J to LGPL 3

**Comment by ChrisVega** [comment]
I, @chrisvega, approve relicensing Discord4J to LGPL 3.

**Comment by manuelgu** [comment]
I, @manuelgu, approve relicensing Discord4J to LGPL 3.

**Comment by 1997mattmcc** [comment]
I, @Arcadeena, approve relicensing Discord4J to LGPL 3.

**Comment by arcadeena** [comment]
I, @Arcadeena, approve relicensing Discord4J to LGPL 3.

**Comment by craftu** [comment]
I, @craftu, approve relicensing Discord4J to LGPL 3.

**Comment by DV8FromTheWorld** [comment]
Congratulations on the license change D4J friend. May your futures be less restricted now :D

**Comment by austinv11** [comment]
We are now LGPL 3 🎉 
Here is the archived issue page:
![lgpl](https://cloud.githubusercontent.com/assets/6373756/24077257/f8e30ba6-0c1d-11e7-9cd9-4c643bfbac48.png)

**Comment by JamesGallicchio** [comment]
I, @JamesGallicchio, approve relicensing Discord4J to LGPL 3.

**Comment by austinv11** [comment]
Okay, *now* we are relicensed (blame Github for screwing up contributor tracking). Here is the real archived page:
![fireshot capture 1 - relicense to gnu lgpl 3 _ - https___github com_austinv11_discord4j_issues_218](https://cloud.githubusercontent.com/assets/6373756/24178564/431c448a-0e80-11e7-9ea1-6ade52484424.png)
