### ISSUE TITLE
Guild / server avaibility

### ISSUE THREAD

**Issue by Dean79000** [austinv11/Discord4J#22]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Bot is unable to interact with server, probably related to release of new official API

### Steps to Reproduce
1. Use a bot Account
2. Add bot to your server with official oAuth url : https://discordapp.com/oauth2/authorize?&client_id=<your-app-id>&scope=bot&permissions=0
3. Login with token using clientBuilder

**Expected behavior:** Retry check server availabity

**Actual behavior:**  Nothing

**Stacktrace (if applicable):** [WebSocketClient@106374177-19] WARN sx.blah.discord.Discord4J - Guild with id <my-server-id> is unavailable, ignoring it. Is there an outage?
**Version affected:** 2.4.2

### Additional Information
Unavailability on official api docs :
https://discordapp.com/developers/docs/topics/gateway#guild-unavailability

**Comment by austinv11** [comment]
This is unfortunately intended behavior. Discord recently made a change so that guilds are no longer available on the `ReadyEvent`. Instead you have to wait for `GuildCreateEvent`s. I plan on making the abstraction for such things a bit better (hopefully) in version 2.5
