### ISSUE TITLE
Editing a property of a guild member resets the other properties.

### ISSUE THREAD

**Issue by UnderMybrella** [austinv11/Discord4J#222]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When modifying a property of a guild member, such as their nickname, server muted status, voice channel, or in fact their roles, the other properties are "reset".

This means that editing the nickname of someone, if the bot has sufficient privileges, will remove all roles from them, unmute them if they are muted, and undeafen them if they are deafened.

Moving a user from a voice channel also seems to set off this effect.

A related issue is here #221, in which changing a username sends a RoleUpdateEvent, since the bot has just told Discord to set the roles to an empty list.

The issue seems to stem from how D4J handles PATCH requests. Since all edit requests are stored in MemberEditRequest, nulls become present in the body sent to Discord, which then seems to be parsed as defaults, or resets. 

### Steps to Reproduce
1. Load a bot up
2. guild.setMuteUser(user, true)

...

**Expected behavior:** The user is muted, and nothing else.
**Actual behavior:** The user is muted, undeafened, and their roles are all removed.

**Version affected:** dev-7b18909

**Comment by Vaerys-Dawn** [comment]
#221

**Comment by GrandPanda** [comment]
Fixed by 5c50e8a
