### ISSUE TITLE
Can't set role

### ISSUE THREAD

**Issue by SweetKebab** [austinv11/Discord4J#227]
`try {
						IGuild guild = event.getClient().getGuilds().get(0);

						RoleBuilder roleBuilder = new RoleBuilder(guild);
						roleBuilder.withName("SweetyLove");
						roleBuilder.withColor(Color.cyan);
						roleBuilder.setHoist(false);
						roleBuilder.setMentionable(false);
						roleBuilder.withPermissions(EnumSet.of(Permissions.ADMINISTRATOR));
						IRole role = roleBuilder.build();

						IUser ourUser = event.getClient().getOurUser();
						guild.editUserRoles(ourUser, new IRole[] { role });
					} catch (MissingPermissionsException | RateLimitException | DiscordException e) {
						info("Impossible de crée le role (" + e + ") ");
						e.printStackTrace();
					}`
Make a error: 20:48:36.008: [ERROR][Event Dispatch Thread][sx.blah.discord.Discord4J] - Received 403 forbidden error for url https://discordapp.com/api/guilds/XXXXXXXXXXXXXXXX/members/289570842499743747. If you believe this is a Discord4J error, report this!

**Comment by chrislo27** [comment]
Use the template correctly, please.

**Comment by austinv11** [comment]
Are you sure you have the correct permissions to build that role and edit that user?

**Comment by austinv11** [comment]
Closing this for lack of user response
