### ISSUE TITLE
NPE related to RequestBuffer

### ISSUE THREAD

**Issue by manuelgu** [austinv11/Discord4J#228]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
A NullPointerException is thrown from the RequestBuffer. So far I stumbled upon two different stacktraces. The first stacktrace was thrown immediately after a 403 error code was received (`channels/{channel.id}/messages`). The second stacktrace randomly occurred.

**Stacktrace:**
1. https://hastebin.com/izevehuqih.pl
2. https://hastebin.com/pepetuzaqa.pl

**Version affected:** Discord4J v2.7.1-SNAPSHOT (dev-f69d22c)

**Comment by quanticc** [comment]
Could you confirm if the second stacktrace is an expired/wrong invite (404)

**Comment by manuelgu** [comment]
@quanticc yes, can confirm that it is infact caused by an invalid invite
