### ISSUE TITLE
voiceStateUpdate NullPointerException

### ISSUE THREAD

**Issue by manuelgu** [austinv11/Discord4J#229]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Quite often a NullPointerException @ `sx.blah.discord.api.internal.DispatchHandler.voiceStateUpdate (572)` is thrown. 

During startup, I call `Discord4j#disableAudio`.

**Stacktrace:** https://hastebin.com/nehezelafe.lua

**Version affected:** Discord4J v2.7.1-SNAPSHOT (dev-f69d22c)

**Comment by austinv11** [comment]
Fixed via 04ee66f
