### ISSUE TITLE
Role updating concurrency issue

### ISSUE THREAD

**Issue by Ikkerens** [austinv11/Discord4J#231]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
In the latest dev snapshot (3063da021ac7c219890e1a093211a985346625b8) I'm noticing an issue when trying to set roles. Although it does not seem to be limited to that. So far I've not been able to acquire more info about the situation but it looks like  Discord4J is no longer in sync with Discord itself.

The snippet below is ran in conjunction with multiple requests, all sent through the RequestBuffer. All the requests properly invoke log.info as seen in the snippet, so they are executed. No exceptions are thrown so nothing to find there.

However, after the snippet below is ran, the role in question still has its initial permissions (after being created).

I tried inquiring to this on the D4J Discord, @austinv11 instructed me to open an issue here.

### Steps to Reproduce
```java
log.info("Setting up role information for " + role.getName());
RequestBuffer.request(() -> {
    role.edit(Color.GREEN, role.isHoisted(), role.getName(), EnumSet.noneOf(Permissions.class), true);
    log.info("Finished setting up role information for " + role.getName());
});
```
Potentially used in combination with more requests, not invoked multithreaded but in fast sequence.

**Expected behavior:** In above snippet, color set to green, permissions gone, role mentionable.

**Actual behavior:** Seemingly random results, sometimes permissions are gone, sometimes role is not mentionable.

**Stacktrace (if applicable):** Not applicable

**Version affected:** dev-3063da0

**Comment by quanticc** [comment]
The steps to reproduce are basically spamming that snippet? Or did you just ran it once and it occurred. Need to know if there was a 403 involved.

**Comment by Ikkerens** [comment]
Well, spamming that snippet yes, but with both the same (I called changeColor and changePermissions sequentially) and different roles.

No 403's as far as I could see in the logs. Couldn't really see anything in the logs. Everything appeared succesful.

However, when calling getPermissions after changePermissions to none, I get an empty permissions set despite the the role still having permissions in the discord client.

**Comment by quanticc** [comment]
I couldn't reproduce it but I see how it could happen. 4a64fe4 might fix it, even though we're not using `synchronized` yet. Can you see if it happens again?

**Comment by Ikkerens** [comment]
Strange, it's consistent for me even with the latest build (58e60970e18a00ff54cd223d905ce6a158031b27).

Regardless, is it possible that two calls to edit for the same role (initiated on different threads) could cause this issue even after your fix?

I just took a look at the source code and it doesn't look like the request is asynchronous, but how is the result of the role updated? Is this sent later on by the Discord server?

**Comment by Ikkerens** [comment]
After toying around today I am no longer capable of reproducing the issues (with no changes to code).
So either I was really unlucky in terms of concurrency, or Discord has fixed something on their end.

Will report back if it comes back.

**Comment by quanticc** [comment]
We will still push something to ensure or at least reduce their occurrence
