### ISSUE TITLE
Unsupported message PRESENCES_REPLACE

### ISSUE THREAD

**Issue by Syl2010** [austinv11/Discord4J#233]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
when the discord servers has reboot, my bot has report in the console this message:
> [HttpClient@4176722-16] WARN sx.blah.discord.Discord4J - Unknown message received: PRESENCES_REPLACE, REPORT THIS TO THE DISCORD4J DEV!

### Steps to Reproduce
1. maybe use a PresenceUpdateEvent
2. Discord servers reboot

...

**Expected behavior:** nothing

**Actual behavior:** a message who want to be report

**Stacktrace (if applicable):** they have no other report.

**Version affected:** Discord4j-2.7.0-shaded

**Comment by GrandPanda** [comment]
As far as I can tell, this is an undocumented gateway event. We have been told in the past to ignore such events. I will confirm this when the outage is resolved.
