### ISSUE TITLE
When the bot doesn't have permissions for a channel, a 403 error is encountered that should be handled with an exception"

### ISSUE THREAD

**Issue by xaanit** [austinv11/Discord4J#243]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already (

### Description
When the bot doesn't have permissions for a channel, a 403 error is encountered that should be handled with an exception

### Steps to Reproduce
1. Make sure the bot doesn't have permissions for a channel (Like a DM with a user who doesn't accept DMs from people who aren't their friend and/or has the bot blocked, not in a channel that literally doesn't have the permission "SEND_MESSAGES")
2. Have it try and send a message

...

**Expected behavior:** Likely throw some sort of MissingPermissionException

**Actual behavior:** `15:19:55.869: [ERROR][RequestBuffer Initial Executor][sx.blah.discord.Discord4J] - Received 403 forbidden error for url https://discordapp.com/api/channels/291065723240054785/messages. If you believe this is a Discord4J error, report this!`

**Stacktrace (if applicable):** N/A
**Version affected:** Attempted on: ac8fdfa

### Additional Information
Relevant code: https://hastebin.com/arikacayof.java (IChannel is an instance of IPrivateChannel in this issue)

**Comment by austinv11** [comment]
We have no way of telling if a user is capable of DMing another user so I'm not sure if we can fix this

**Comment by GrandPanda** [comment]
We cannot directly "fix" this with a pre-check. However, at the moment it is impossible for a user to properly handle this case. It reveals an inherent problem in the Requests system in that many issues are logged rather than provided as an exception for user handling. This should be addressed in the future.
