### ISSUE TITLE
`user.getRolesForGuild` returns empty sometimes

### ISSUE THREAD

**Issue by isteinvids** [austinv11/Discord4J#251]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
`user.getRolesForGuild` returns an empty list, apparently only for servers I'm owner of.

### Steps to Reproduce
1. Run `user.getRolesForGuild` on a server you're owner of

...

**Expected behavior:** `user.getRolesForGuild` returns the proper roles

**Actual behavior:** `user.getRolesForGuild` is empty

**Version affected:** 5a3ea4c and after

**Comment by austinv11** [comment]
Fixed via 6fb043a
