### ISSUE TITLE
404 errors on requests to user endpoints

### ISSUE THREAD

**Issue by JamesGallicchio** [austinv11/Discord4J#252]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
D4J gets a 404 error on requests to user endpoints.
It seems to occur when getting users by their ID, but is inconsistent. However, it seems to happen consistently for some user IDs

### Steps to Reproduce
1. Attempt to get a user by their ID, though seemingly inconsistent

**Expected behavior:** The user object was gotten

**Actual behavior:** A 404 error

**Stacktrace (if applicable):** No stack trace, but error message `Received 404 error, please notify the developer and include the URL (https://discordapp.com/api/users/[id])`

**Version affected:** dev latest (059b5eb)

### Additional Information
* Verified across multiple users, seems to also occur internally in D4J

**Comment by austinv11** [comment]
Fixed via 6376c7a
