### ISSUE TITLE
PMs throw an NPE

### ISSUE THREAD

**Issue by SamboyCoding** [austinv11/Discord4J#257]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)  (they told me to post an issue!)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Upon sending or receiving a private message, an NPE occurs in DiscordUtils, because of a missing PM check, so the bot calls getGuild() on a PM message, returning null, then tries to get all the users in that guild.

### Steps to Reproduce
1. Send or receive a PM
2. Observe.

**Expected behavior:** The bot would not error.

**Actual behavior:** An NPE occurs.

**Stacktrace (if applicable):** https://hastebin.com/ihemahoqez.txt 

**Version affected:** `Discord4J v2.7.1-SNAPSHOT (dev-2beeb98)`

### Additional Information
Confirmed with red on the D4J server.
Caused by [this commit](https://github.com/austinv11/Discord4J/commit/cd3815289737572f9bf2074cd7891fbf510c6d56) then broken again by [this commit](https://github.com/austinv11/Discord4J/commit/0c117aa33eb563716c6780277623982fc7be7972)

**Comment by chrislo27** [comment]
Fixed as of https://github.com/austinv11/Discord4J/commit/0f0603059b8fe4495048645a7730ac3ddd1ee16b
