### ISSUE TITLE
MessageUpdateEvent fired when new Embed is sent.

### ISSUE THREAD

**Issue by xaanit** [austinv11/Discord4J#260]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Bots (and users) making an embed leads to a MessageUpdateEvent, if the bot makes an embed in the event it calls infinitely.

### Steps to Reproduce
1. Make a MessageUpdateEvent that sends an embed (or doesn't, this is only needed if you wish to see it go infinitely)
2. Have any bot make an embed

...

**Expected behavior:** It shouldn't call when an embed is sent for the first time.

**Actual behavior:** It does.

**Stacktrace (if applicable):** N/A

**Version affected:** Commit `0f06030`

### Additional Information
- [Code used when bug was found](https://hastebin.com/orulugiret.java)
- Likely due to the fact that MessageUpdateEvent is fired when new embedded content is added to a message not in D4J's cache, i.e right at sending.
- I feel like MessageEmbedEvent should be called instead, no?

**Comment by GrandPanda** [comment]
Fixed by 04cd777
