### ISSUE TITLE
Reactions in a RequestBuffer send out of order

### ISSUE THREAD

**Issue by nerd** [austinv11/Discord4J#261]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
when attempting to add multiple reactions, each via a RequestBuffer, the order is not guaranteed.

### Steps to Reproduce
1. add different reactions, each wrapped in a RequestBuffer request
2. ???
3. profit

**Expected behavior:** the reactions are added in the order of calling the requests

**Actual behavior:** they be out of the order

**Version affected:** `90ba106` also `04cd777`

### Additional Information
please fix

**Comment by austinv11** [comment]
Ordering isn't guaranteed by RequestBuffer on its own. If you call get() between calls or use RequestBuilder the ordering issue could be fixed.
