### ISSUE TITLE
Edited roles hierarchy is too high.

### ISSUE THREAD

**Issue by egold555** [austinv11/Discord4J#263]
### Description
Whenever I try to make my bot move me to a certain role I get this exception.

### Steps to Reproduce
1. Make a discord bot
2. Give it every perm on your server
3. Make a role with non admin powers
4. Right code to make it move you to that role that you just created
...

**Expected behavior:** 
It should move me to that certain role

**Actual behavior:** 
Did not move me and threw a exception in the console.

**Stacktrace (if applicable):** 
https://pastebin.com/ijCauyFW

**Version affected:**
Discord4J-2.7.0-shaded

### Additional Information
My code: https://pastebin.com/HbUQP12Y 
(Both methods I tried did not work and produced the same error)

**Comment by chrislo27** [comment]
The server owner has the maximum permissions (it overrides Administrator). Since the bot is not the owner of the server, it cannot move you.

**Comment by egold555** [comment]
I am trying to move a person who is not the owner and I still get the same error

**Comment by austinv11** [comment]
What are your bot's roles (in positional order) and the user's you are trying to change?

**Comment by egold555** [comment]
Figured it out. Did not relise that the role order mattered. Thanks for your time.
