### ISSUE TITLE
Random Null value with IMessage#getReactionForUnicode(Emoji)

### ISSUE THREAD

**Issue by Syl2010** [austinv11/Discord4J#278]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Sometimes, this function work correctly, at other times, he send a Null value, with the same Emoji on different messages.

### Steps to Reproduce
1. Create some message with a Reaction.
2. Get the unicode of the Emoji's reaction with EmojiManager and use it for catch the reaction with IMessage#getReactionForUnicode(Emoji).
3. repeat it on several messages with the same reaction.

**Expected behavior:** IMessage#getReactionForUnicode(Emoji) return the reaction

**Actual behavior:** IMessage#getReactionForUnicode(Emoji) return null

**Stacktrace (if applicable):** https://pastebin.com/p8tedA1q

**Version affected:** Discord4j-2.8.1

### Additional Information

EDIT, The src file : https://pastebin.com/YFzZYwBM

**Comment by firestar115** [comment]
The stacktrace says that the reaction you want to remove is null. This means that the message doesn't have that reaction on it.

**Comment by Syl2010** [comment]
he have the reaction, i create the reaction in the code before i remove it:
If you want, i can share the src class.

**Comment by firestar115** [comment]
The NPE comes from trying to get something off of the reaction, which means `le_message.getReactionByUnicode(EmojiManager.getForAlias(emoji))` must be null.

As you can see in the stacktrace, the "zero" is null.

If you try entering `\:zero:` in Discord, it won't give you a unicode character.

**Comment by Syl2010** [comment]
i shared the src code. the reaction is create by the bot, and I delete all bot's reactions if he receive the :x: reaction. Sometimes, the delete work fine, at other time, he failed with NPE, but the :x: reaction is delete in all times.

**Comment by Syl2010** [comment]
Record of the bug : https://www.dropbox.com/s/ze21yruhhxvcpuf/2017-04-30_19-02-42.mov?dl=1
The bug is random. It's appear at 00:35

**Comment by Syl2010** [comment]
I try to code a fix for a better detection of the error. When the message has the error with getReactionForUnicode(Emoji), if I retry to get the reactions on the same message, he send the same error.

New src files : https://pastebin.com/SsKDDqVB
Console output : https://pastebin.com/2MeBQCvH

when getReactionForUnicode return null, I send a error message and I re-register the class in the dispatcher.

**Comment by austinv11** [comment]
Gonna need you to be more explicit. 
Where are you specifically getting the reaction to delete?

**Comment by Syl2010** [comment]
I getting the reaction from the message, used in the construction of the object

**Comment by Syl2010** [comment]
I found the bug. The IMessage object register at the construction of the object is not update when i try to remove reaction. But the IMessage object attach on reactionAddEvent is update. I can fix the bug on my part.
But i guess the IMessage object must be updated before a getReaction function can be used on it, isn't it ?
