### ISSUE TITLE
Fix Typo in README.md

### ISSUE THREAD

**Issue by SubtypeZero** [austinv11/Discord4J#280]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
There's an issue with the maven example. The "J" in the artifactId is not capitalized.

### Steps to Reproduce
1. Try to use the example (the dependency can't be found)

**Expected behavior:** Dependency gets imported

**Actual behavior:** Dependency does not get imported

**Version affected:** All

### Additional Information
https://i.gyazo.com/10c4aed8744efd06323bb911a543838a.png

**Comment by xaanit** [comment]
```xml
        <dependency>
            <groupId>com.github.austinv11</groupId>
            <artifactId>Discord4j</artifactId>
            <version>2.8.0</version>
        </dependency>
```

Maven works for me with both the lowercase and Capital J
```xml
        <dependency>
            <groupId>com.github.austinv11</groupId>
            <artifactId>Discord4J</artifactId>
            <version>2.8.0</version>
        </dependency>
```

If this was an actual issue, it would have been fixed by now. It's an error somewhere on your end.
