### ISSUE TITLE
InterruptedException after losing connection.

### ISSUE THREAD

**Issue by davidkoplik** [austinv11/Discord4J#281]
### Description
After multiple reconnect attempts, the bot throws InterrupedException.

### Steps to Reproduce
1. Run your bot
2. Turn off your internet connection.
3. After around 7 reconnect attempts, an InterruptedException will be thrown.

...

**Expected behavior:** Keep reconnecting until connection is established.

**Actual behavior:** The bot crashed (InterrupedException).

**Stacktrace (if applicable):** https://hastebin.com/jusopironi.pl

**Version affected:** 2.8.1

**Comment by austinv11** [comment]
Did you change the max number of reconnects allowed?

**Comment by davidkoplik** [comment]
Yes, I have tried putting larger numbers there.

**Comment by GrandPanda** [comment]
Fixed via https://github.com/austinv11/Discord4J/commit/d2b3014a1d0ff2fa390dfd17889585af956c13d4.
