### ISSUE TITLE
RequestBuffer creates many threads and never kills them

### ISSUE THREAD

**Issue by BrutalCSkakan** [austinv11/Discord4J#291]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The RequestBuffer spawns infinite amount of threads

### Steps to Reproduce
1. Have a bot
2. Do something with the RequestBuffer, wait for a while(some days probably)
3. Threads will be over ninethousand!

...

**Expected behavior:** The RequestBuffer threads should die

**Actual behavior:** The threads didn't die

**Stacktrace (if applicable):**

**Version affected:** [The version of Discord4J]
2.8.1

### Additional Information
https://cdn.discordapp.com/attachments/208296894265294849/313728964675895307/unknown.png

**Comment by BrutalCSkakan** [comment]
Looks like it's the following code that triggers this bug:

RequestBuffer.request(() -> {
                try {
                    messageId.edit(null, embedBuilder.build());
                } catch (MissingPermissionsException e) {
                    e.printStackTrace();
                } catch (DiscordException e) {
                    e.printStackTrace();
                }

            });

**Comment by austinv11** [comment]
Fixed via cdfb2c1
