### ISSUE TITLE
getWebhookLongID causes a NullPointerException if the message has no associated webhook

### ISSUE THREAD

**Issue by NorbiPeti** [austinv11/Discord4J#293]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
If the message doesn't have a webhook ID set, the getWebhookLongID method generates a NullPointerException and there's no way of determining if there is a webhook ID. I believe a possible fix would be to use `long` instead of `Long` for the ID or set a default value of 0.

### Steps to Reproduce
1. Use IMessage.getWebhookLongID()
2. Send a message without using a webhook

...

**Expected behavior:** The method returns 0 or another specified value.

**Actual behavior:** A NullPointerException occurs inside the method.

**Stacktrace (if applicable):** https://pastebin.com/uhwiJuHk

**Version affected:** [Latest commit as of now](https://github.com/austinv11/Discord4J/commit/542bd422d7ba1ab6b9d06ea26018f62b2fa38ae2)

**Comment by GrandPanda** [comment]
It will now return 0.
