### ISSUE TITLE
No audio when using LavaPlayer until disconnect exception, then works fine

### ISSUE THREAD

**Issue by Babbie** [austinv11/Discord4J#295]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
We've been making a bot using LavaPlayer and D4J and it suddenly stopped working, without us changing any code. We've tried using D4J 2.8.0 and 2.8.1 and neither creates any sound even though it did work fine before. It's not the song, as no youtube url will work. We do get an exception when we make our bot disconnect however:
```
java.lang.NullPointerException
    at sx.blah.discord.api.internal.UDPVoiceSocket.shutdown(UDPVoiceSocket.java:157)
    at sx.blah.discord.api.internal.DiscordVoiceWS.disconnect(DiscordVoiceWS.java:144)
    at sx.blah.discord.handle.impl.obj.VoiceChannel.leave(VoiceChannel.java:143)
    at org.twobits.adagio.audio.TrackScheduler$1.run(TrackScheduler.java:51)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```
Note that after that disconnect, if we make it reconnect and start playing again in the dev-SNAPSHOT version any new music request DOES play perfectly. After a shutdown and reboot of the bot it will not work again until we make it disconnect and throw that same exception. In the latest RELEASE it doesn't play at all; after the reconnect it only makes the green "activity" circle glow without making any sound.

**Comment by GrandPanda** [comment]
Can you see if you can still reproduce this after the above commit?

**Comment by Babbie** [comment]
I can't right now, but tomorrow I will try. I still need to choose the `dev-SNAPSHOT` version, correct?

**Comment by GrandPanda** [comment]
No problem. Either reimport with that or use the commit hash https://github.com/austinv11/Discord4J/commit/2732a6c2eb1a1842bddeb362228e6287df3a8c62.

**Comment by Babbie** [comment]
It seems I celebrated too soon. It worked perfectly the first launch, but after I shut down the bot and restarted it, it didn't work anymore, not even after I made it disconnect/reconnect to the voice channel.

**Comment by GrandPanda** [comment]
Can you provide an updated stacktrace? I don't think it can be the same error as before.

**Comment by Babbie** [comment]
There is no error anymore at all, there's just no audio playing.

**Comment by austinv11** [comment]
We cannot look into this issue without more info. So it would be awesome of you gave us some trace-level logs as well as *very* specific steps to reproduce this issue.

**Comment by Babbie** [comment]
Simply run the music-player branch of [this project](https://github.com/two-bit-productions/Adagio) and try using the play command with any YouTube URL, e.g. `!play https://www.youtube.com/watch?v=6n8U_lgkGIY` If you need me to be more specific, please do ask.

**Comment by austinv11** [comment]
I am not familiar enough with your project. I'd prefer it if you could provide what I asked for originally. It can help us figure out if this is a D4J issue, lavaplayer issue or simply a user issue.

**Comment by Babbie** [comment]
A trace log is [here](https://gist.github.com/Babbie/adc53f40df0e7bf8524c054f65aaafc4). I think I'm pretty much following LavaPlayer's example for D4J perfectly in my code. I don't see what I'm doing differently, at least.

**Comment by austinv11** [comment]
That is pretty much unreadable due to raw http logging. Can you disable it from log4j and then re-report? I've been told you can disable it using this:
```
log4j.logger.org.mortbay.log=fatal
log4j.logger.org.apache.http=fatal
log4j.logger.org.apache.http.headers=fatal
log4j.logger.org.apache.http.wire=fatal
```
Additionally, as a result of logging raw http traffic, your token has been revealed. I recommend resetting it.

**Comment by ArsenArsen** [comment]
Heh.. I pointed that out already. RIP.

Check your logs people :)

**Comment by Babbie** [comment]
Yeah, I figured the key would be in there somewhere. It doesn't really matter, since the bot is completely unused as of yet.
When resetting the token though, something interesting happened: the first time I started the bot with the new key, it worked again. After a restart, however, it went back to not working.
(Here is a new log.)[https://gist.github.com/Babbie/1e6b0400f38462e92a6fa8b4efc1cf31]

**Comment by austinv11** [comment]
Is the bot in the voice channel already when you restart it?

**Comment by Babbie** [comment]
Not normally, no. It might have been in that log, [here's a new one just in case.](https://gist.github.com/Babbie/68dbf5b9af6175eb38134419d5436da4)
