### ISSUE TITLE
Server Mute Self throws Permission Exception

### ISSUE THREAD

**Issue by Techtony96** [austinv11/Discord4J#296]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When trying to server mute my bot, it throws the `Edited roles hierarchy is too high` error.

### Steps to Reproduce
1. Have a role at the highest highest hierarchy level with Administrator permissions
2. Assign your bot to that role
3. Try to server mute the bot. `guild.setMuteUser(client.getOurUser(), true);`

...

**Expected behavior:** 
The bot should now be server muted

**Actual behavior:**
The permission exception is thrown:

**Stacktrace (if applicable):** 
https://pastebin.com/0wxBayDz

**Version affected:** 2.8.0 Testing was done on

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Techtony96** [comment]
Just tested on dev-snapshot and same thing happens

**Comment by craftu** [comment]
isn't this intended? server muting is separate from local muting

**Comment by MinnDevelopment** [comment]
You're able to server mute/deafen regardless of role hierarchy

**Comment by oopsjpeg** [comment]
didn't read the first step. i'm a moron, continue
