### ISSUE TITLE
Unknown Message

### ISSUE THREAD

**Issue by darkhax** [austinv11/Discord4J#3]
Received the following console output while leaving my bot Idle on a private server. Not sure what significance it might have, but it asked to be reported here. [This](https://gist.github.com/darkhax/7ef0a4e73319d10395f6) is a Gist containing the error message. Session IDs and user IDs have been omitted intentionally.

**Comment by lclc98** [comment]
This is the packet for connecting/disconnecting from the voice server(depends on the channel id is null or not) from what I have seen when testing, I am currently working on implementing voice into Discord4J so that this should not be there in the future.

**Comment by austinv11** [comment]
As @lclc98 had said, this will be removed in the future, but thanks for reporting it!
