### ISSUE TITLE
Removing reactions with emotes from external guilds throws NPE

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [austinv11/Discord4J#305]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

(not sure if related to #278)

### Description
`IReaction`s with emojis from guilds that the current bot/user is not part of return true for `isCustomEmoji()` but return `null` for `getCustomEmoji()` - for the obvious reason that the emoji isn't accessible. The problem is when `Message.removeReaction(IUser, IReaction)` is called, it throws NullPointerException because of a conditional that looks something like `reaction.isCustomEmoji() ? reaction.getCustomEmoji().getName() ...`.

### Steps to Reproduce
1. Obtain reaction with emote from an external guild
2. `Message.removeReaction(IUser, IReaction)`

**Expected behavior:** Reaction should be removed

**Actual behavior:** `NullPointerException`

**Stacktrace (if applicable):** I don't have it with me right now because I haven't gotten around to properly setting up logback and it wasn't saved, but the NPE is from L608 of `Message.removeReaction(IUser, IReaction)` on the `reaction.getCustomEmoji().getName()` call.

**Version affected:** 2.8.1 (presumably 2.8.2 as well because it appears to have the same code but I haven't tried)

### Additional Information
This is an implementation of removeReaction that should work
```java
	@Override
	public void removeReaction(IUser user, IReaction reaction) {
		IMessage message = reaction.getMessage();
		if (!this.equals(message))
			throw new DiscordException("Reaction argument's message does not match this one.");

		if (!user.equals(client.getOurUser())) {
			DiscordUtils.checkPermissions(client.getOurUser(), message.getChannel(), EnumSet.of(Permissions.MANAGE_MESSAGES));
		}

		try {
			String emoteString;
			if (reaction.isCustomEmoji()) {
				if (reaction.getCustomEmoji() != null) {
					emoteString = reaction.getCustomEmoji().getName() + ":" + reaction.getCustomEmoji().getStringID();
				} else {
					// emoji contains the actual ID of the emote. Discord doesn't appear to care that you have the correct name
					emoteString = "idk:" + reaction.emoji;
				}
			} else {
				emoteString = URLEncoder.encode(reaction.toString(), "UTF-8").replace("+", "%20");
			}
			((DiscordClientImpl) client).REQUESTS.DELETE.makeRequest(
					String.format(DiscordEndpoints.REACTIONS_USER, message.getChannel().getStringID(), message.getStringID(),
							emoteString,
							user.getLongID() == client.getOurUser().getLongID() ? "@me" : user.getStringID()));
		} catch (UnsupportedEncodingException e) {
			Discord4J.LOGGER.error(LogMarkers.HANDLE, "Discord4J Internal Exception", e);
		}
	}
```

**Comment by GrandPanda** [comment]
Reactions have been completely reworked in the `change/reactions` branch which should fix this issue. It currently needs some testing before it can be merged.
