### ISSUE TITLE
Get Roles error if no roles are there

### ISSUE THREAD

**Issue by SaubereSacheLP** [austinv11/Discord4J#307]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
If you try to get the roles of a user, but he has not got roles.

### Steps to Reproduce
1. Have this code implemented:
https://hastebin.com/ularojovej.swift

2. Send a message in a channel without having roles (in my case 218691112833908736)

**Expected behavior:** It should skip the foreach loop and execute the code after the try catch

**Actual behavior:** Its breaking after the try catch

**Stacktrace (if applicable):** https://hastebin.com/quwiyoyaza.md

**Version affected:** latest

### Additional Information
Discord: https://alphaantileak.net/discord.php

P.S.: for now I removed the code

**Comment by austinv11** [comment]
Is this the latest release? (2.8.2) or latest snapshot? (d26b8dc)

Also, from that screenshot it appears that either a guild with the id `218691112833908736` or the user with id `214044419446407169` doesn't exist in that guild. Can you verify if that is the case?

**Comment by SaubereSacheLP** [comment]
Hi, im using the latest release, and the user and the guild are existing!

**Comment by austinv11** [comment]
You might be trying to delete the @everyone role (which is impossible). You should modify your code to check for this using `IRole#isEveryoneRole`

**Comment by SaubereSacheLP** [comment]
Ah yeah that was the problem, thank you ;)
