### ISSUE TITLE
NoSuchFieldError: ALLOW_MISSING_VALUES

### ISSUE THREAD

**Issue by Codeloper** [austinv11/Discord4J#309]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Trying to start a Spigot plugin with shaded Discord4J 2.8.0 (where Gson was replaced by Jackson) or following causes following exception:

```
java.lang.NoSuchFieldError: ALLOW_MISSING_VALUES
        at sx.blah.discord.api.internal.DiscordUtils.<clinit>(DiscordUtils.java:75) ~[?:?]
        at sx.blah.discord.api.events.EventDispatcher.<init>(EventDispatcher.java:73) ~[?:?]
        at sx.blah.discord.api.internal.DiscordClientImpl.<init>(DiscordClientImpl.java:135) ~[?:?]
        at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:280) ~[?:?]
        at sx.blah.discord.api.ClientBuilder.login(ClientBuilder.java:300) ~[?:?]
```

When using Discord4J 2.7.0 everything is fine. I've tried various things with different shade configuration but I couldn't fix.

**Version affected:** 2.8.0 following

**Comment by xaanit** [comment]
Uhm, can we see the code that comes with you creating a client? How to reproduce it?

**Comment by TsundereBug** [comment]
Also if you could run this plugin in a development environment so we could see the source lines and not `?:?`?

**Comment by TsundereBug** [comment]
I checked line 75 of DiscordUtil and it doesn't seem like it should error there. Do you get any different results on 2.8.2? And also, does this issue happen on plugin load or on server load?

**Comment by Codeloper** [comment]
```
public DiscordManager( final DiscordPlugin plugin ) {
		
	this.plugin = plugin;
		
	client = createClientAndLogin( plugin.getConfigurationGateway().getDiscordToken() ); // line 29
	
	guild = client.getGuildByID( plugin.getConfigurationGateway().getDiscordGuild() );
		
	EventDispatcher dispatcher = client.getDispatcher();
	dispatcher.registerListener( this );
		
}

private IDiscordClient createClientAndLogin( final String token ) {
		
	final ClientBuilder clientBuilder = new ClientBuilder();
	clientBuilder.withToken( token );
		
	try {
			
		return clientBuilder.login(); // line 45
			
	} catch ( final DiscordException e ) {
		e.printStackTrace();
	}
		
	return null;
}
```

```
        at cologne.tom.discord.DiscordManager.createClientAndLogin(DiscordManager.java:45) ~[?:?]
        at cologne.tom.discord.DiscordManager.<init>(DiscordManager.java:29) ~[?:?]
        at cologne.tom.discord.DiscordPlugin.onEnable(DiscordPlugin.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1104]
```

I've tried it with 2.8.2, too. Problem occurs on plugin load.

**Comment by TsundereBug** [comment]
The error still is on line 75 on 2.8.2?

**Comment by Codeloper** [comment]
I think so, but I'm just doing some other tests and will write back later.

**Comment by austinv11** [comment]
How is d4j being provided by your plugin?

**Comment by Codeloper** [comment]
The error is still on line 75 with 2.8.2.

Normally it is provided by a dependency plugin where every needed dependency is shaded (bad internet link :/). I've tried to shade it directly with the plugin, but it didn't changed anything.
I've tried various versions and classifiers and every configuration I could imagine and tried to build Discord4J myself and include it, but had no success.

**Comment by TsundereBug** [comment]
The `ALLOW_MISSING_VALUES` seems to be on line 7**6** of DiscordUtils.

It seems to be related to Jackson, are you sure you have the right version of Jackson?

**Comment by Codeloper** [comment]
I was wondering about that, too. I declared various versions of jackson (and in every one the field existed), but could not change anything.

**Comment by TsundereBug** [comment]
Hmm. It would error earlier if Jackson wasn't in the classpath. How are you assembling the plugin jar again?

**Comment by UninterestinAcc** [comment]
As a wild guess - spigot or some other plugin might be using a different version of jackson.

**Comment by TsundereBug** [comment]
Hold up, I think I can check spigot dependencies.

**Comment by TsundereBug** [comment]
```xml
<dependencies>
    <dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>2.6</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>com.googlecode.json-simple</groupId>
        <artifactId>json-simple</artifactId>
        <version>1.1.1</version>
        <type>jar</type>
        <scope>compile</scope>
    </dependency>
    <!--  bundled with Minecraft, should be kept in sync  -->
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>17.0</version>
        <scope>compile</scope>
    </dependency>
    <!--  bundled with Minecraft, should be kept in sync  -->
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.2.4</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.avaje</groupId>
        <artifactId>ebean</artifactId>
        <version>2.8.1</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>1.17</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>net.md-5</groupId>
        <artifactId>bungeecord-chat</artifactId>
        <version>1.10-SNAPSHOT</version>
        <type>jar</type>
        <scope>compile</scope>
    </dependency>
    <!--  testing  -->
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest-library</artifactId>
        <version>1.3</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```
It uses `gson` and `json-simple`. Shouldn't have conflicts.

**Comment by electricman226** [comment]
What other plugins are running on this server? Try on a raw spigot server without any other plugins to see if you still get an error.

**Comment by Codeloper** [comment]
Sorry for late reply. On a clean server install, it works fine. I'm now trying to find out which plugin causes interference.

**Comment by ArsenArsen** [comment]
Your classpath contains D4J version which is not the same as the one at compile time, which stops new ones from being loaded. If the class was moved around or whatever this happens.
