### ISSUE TITLE
When a bot triggers a mention of itself, it triggers MentionEvent.

### ISSUE THREAD

**Issue by aimadtakhtoukh** [austinv11/Discord4J#312]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When making a parrot bot that reacts upon mentions, the bot repeats what has been said. The repeat causes it to trigger again, repeating what he said ad nauseam or until hitting the rate limit.

### Steps to Reproduce
1. Create a listener with MentionEvents.
2. Make it repeat itself with 
`new MessageBuilder(event.getClient())
.withChannel(event.getMessage().getChannel())
.withContent(event.getMessage().getContent()).build();`

...

**Expected behavior:** According to xaanit, the bot should ignore mentions of itself.

**Actual behavior:** When a bot sends a message mentionning itself, the MentionEvent triggers.

**Version affected:** 2.8.3

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by GrandPanda** [comment]
This is intended behavior. The event is fired when the mentions array from Discord contains the bot user. It is simple to check if the author of the message is the bot user in your event listener.

**Comment by JamesGallicchio** [comment]
Yet we ignore the bot's own messages in MessageReceiveEvent for favor of MessageSentEvent- having MentionEvent trigger on the bot's own messages is very confusing (and frankly, rather arbitrary) "intended behavior"

**Comment by GrandPanda** [comment]
That is something I would change given the opportunity. Unfortunately that decision was made almost 2 years ago and cannot be changed. It is anything but arbitrary. The event is fired if the mentioned users array contains the bot user.

**Comment by JamesGallicchio** [comment]
Possible v3 change? 🤔
