### ISSUE TITLE
always get "unauthorized"

### ISSUE THREAD

**Issue by alexpmorris** [austinv11/Discord4J#315]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J (**maybe**)
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
can't seem to login, even with token.  maybe I am missing the place where I should also put my "clientid"?

### Steps to Reproduce
1. login with token
2. exception error

**Expected behavior:** it should login

**Actual behavior:** login failed

**Stacktrace (if applicable):** 
```
Exception in thread "main" sx.blah.discord.util.DiscordException: 
Exception (DiscordException) occurred while logging in: 
Error on request to https://discordapp.com/api/users/@me. Received response code 401. 
With response text: {"code": 0, "message": "401: Unauthorized"}
	at sx.blah.discord.api.ClientBuilder.login(ClientBuilder.java:304)
	at EmptyBot.main(EmptyBot.java:112)
	at whalebot.main(whalebot.java:29)
```

**Version affected:** 2.8.3

### Additional Information
I have a token, but no matter what I try, still keep getting an error on request to "https://discordapp.com/api/users/@me" {"code": 0, "message": "401: Unauthorized"} - even tried stepping in the code and replacing @me with my userid, it calls me a snowflake instead but still stops.  I figure I'm probably just missing something simple, but it's just not coming to me.  Not sure if it's related, but I didn't "Create a Bot User" to the app.  Couldn't find enough info on it to perform that "irreversible action".

I also tried with the EmptyBot project as well, but basically all I'm doing is:

``IDiscordClient client = createClient(token, true); // Gets the client object (from the first example)``

tried it with true and false.  build() works just fine, but it always dies at login().

Apologize if I'm just missing something simple here, but I figure I can't be the only making this "mistake" either.  Thanks!

For the record, I had no problem interfacing to discord via their webhooks (though, of course, that's not *interactive*).

**Comment by decyg** [comment]
You must create an application and an associated bot user on the application page and use the token provided there, a user token or similar will not work. I'm closing this issue as it's not D4J related, if you still have issues please join the discord server and mention me.

**Comment by alexpmorris** [comment]
That's what I was missing, and couldn't seem to find that little tidbit I needed - they really didn't make it very clear (at least not to me).  And I thought the "key" was then "token"!  Thanks for setting me straight on it, should be all good from here.  If you're on STEEMIT shoot me your userID and I'll tip you some STEEM! :)

**Comment by alexpmorris** [comment]
Just wanted to share with you what I put together since you got me passed that auth issue!  Really great work you're doing with this.  I also gave you and DiscordJ a shoutout in the post as well, since there's no way I could have put this together so quickly without it.

If you ever decide to join STEEMIT.com shoot me a message and I'd be happy to introduce you to the community and have them all (including me) throw some votes (aka crypto money) your way as a welcome and a thank you! :)

https://steemit.com/beyondbitcoin/@alexpmorris/steemit-world-meet-the-discord-community-s-latest-member-whalebot
