### ISSUE TITLE
TrackSkippedEvent Nullpointer

### ISSUE THREAD

**Issue by PeterDevStop** [austinv11/Discord4J#317]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [ ] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
[Every time I call `event.getNextTrack();` I get a NullPointerException, but `event.getTrack();` does not through an exception.]

### Steps to Reproduce
1. Add this method to your listener: `@EventSubscriber
	public void onTrackSkipEvent(TrackSkipEvent event){
                   System.out.println(event.getNextTrack().getTotalTrackTime());
        }`
2. Run the bot

...

**Expected behavior:** Program prints the track time

**Actual behavior:** Program threw a NullPointerException

**Stacktrace (if applicable):** https://pastebin.com/aKdpf0AX

**Version affected:** 2.8.4

### Additional Information
null

**Comment by austinv11** [comment]
`event.getNextTrack()` is null in your case

**Comment by PeterDevStop** [comment]
But my queue contained 751 tracks, and the one playing was the first track.

**Comment by austinv11** [comment]
Gonna need more info then.
* Does your bot still play music when this occurs?
* Is your bot on multiple guilds?
* Can you verify guild sizes before/after this occurs?
* Is there a case where this occurs consistently?

**Comment by austinv11** [comment]
The guild size was a typo, I meant queue size

**Comment by PeterDevStop** [comment]
***Queue size: 172 indexes -> 742MB***

**Comment by austinv11** [comment]
That tells me nothing, I need to know both before and after as well as how you are getting that number.

**Comment by PeterDevStop** [comment]
fixed

**Comment by PeterDevStop** [comment]
> 3: Before: Queue size: 171 indexes | After: Queue size: 170 indexes
> 4: Method for getting queue size: System.out.println(this.audioP.getPlaylistSize());

**Comment by austinv11** [comment]
Are you 100% certain ALL your tracks are actually non-null?

**Comment by ArsenArsen** [comment]
`this.audioP.getPlaylist().stream().filter(Objects::nonNull).collect(Collectors.toSet())`
