### ISSUE TITLE
Discord4J loses Websocket connection over time, especially on more idle servers

### ISSUE THREAD

**Issue by RyanMorrison04** [austinv11/Discord4J#32]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Discord4J intermittently loses connection to the Discord websocket with an "UNKNOWN" reason. It does not attempt reconnection but simply terminates itself.

### Steps to Reproduce
1. Connect Discord4J to the Discord API, ideally in a generally idle server.
2. Wait for the timeout.

**Expected behavior:** Discord4J should be able to maintain a Websocket connection over a long period of time in accordance with heartbeats as defined in the Discord API documentation.
**Actual behavior:** Discord4J, especially on idle servers, cannot maintain a Websocket connection over a long period of time (a few hours).

**Stacktrace (if applicable):** http://pastebin.com/z1eGtJFr

**Version affected:** 2.4.7

**Comment by decyg** [comment]
Are you running it as a daemon, ie using .setDaemon(true) on the ClientBuilder object? Also i'd suggest joining the discord4j channel on discord, Austin is about fairly frequently.

**Comment by RyanMorrison04** [comment]
Yes, I have tried both with daemon and without daemon modes.

**Comment by iabarca** [comment]
It is expected to get a 1000/1001 error eventually, due to CloudFlare resetting the websocket proxy for instance.

The intended way to deal with these is to listen for the `DiscordDisconnectedEvent` and perform a login retry there. There is no auto-reconnect/resume feature implemented yet.

**Comment by RyanMorrison04** [comment]
Is it safe to assume it's on the roadmap though? Seems like something the library should transparently handle instead of forcing clients to implement their own logic.

**Comment by austinv11** [comment]
Yes, something like ClientBuilder#withReconnects() is planned for 2.5.0

**Comment by phantamanta44** [comment]
About the auto reconnecting: shouldn't isReady() return false if the websocket dies?
