### ISSUE TITLE
NSFW Channels doesn't need to have nswf in their name anymore

### ISSUE THREAD

**Issue by S0ngfu** [austinv11/Discord4J#326]
### Prerequisites
* [✓] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [✓ ] This issue specifically has something to do with Discord4J
* [✓ ] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
[Description of the issue]
In the current time, isNSFW() (Channel.java line 583) is looking to see if the channel name contains nsfw when it is not needed anymore.

### Steps to Reproduce
1. [First step]
Try to run NSFW commands in channels that allow them but doesn't have a name with nsfw in them.

**Expected behavior:** [What was supposed to happen]
isNSFW() should check if the permission for NSFW channel is granted. Not if the name contains nsfw.

**Actual behavior:** [What actually happened]
It only checks if name contains nsfw.

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of Discord4J]
Discord4J v2.8.5-SNAPSHOT (dev-3e16305)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by GrandPanda** [comment]
The nsfw channel property currently does not function correctly. It will be reimplemented when Discord fixes it.

**Comment by GrandPanda** [comment]
Implemented as of https://github.com/austinv11/Discord4J/commit/94ef27d472cd0134167f3571c5d7a659fbc175f2.
