### ISSUE TITLE
Bot kicked all users

### ISSUE THREAD

**Issue by TodesRitter** [austinv11/Discord4J#346]
### Description
Today at 0:38 in Midnight the Bot i created kicked all users without any reason. i didnt create any line with a kick command or something else. Could this be a security leak or a injection ?

**Version affected:** 2.8.4

### Additional Information
https://github.com/TodesRitter/DiscordBot

**Comment by lclc98** [comment]
Your bot token is public, it is possible that someone used it to kick users.

**Comment by GrandPanda** [comment]
Your authorization token is in your repo. Someone used it to login and kick the users. You should reset it and not make it public in the future.

**Comment by TodesRitter** [comment]
i made it public after this happend. Strange.
