### ISSUE TITLE
IChannel#getTopic doesn't work with emoji's

### ISSUE THREAD

**Issue by Mendess2526** [austinv11/Discord4J#347]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
`IChannel#getTopic` doesn't like emoji's

### Steps to Reproduce
1. Change a channel topic to include an emoji
2. call `getTopic()` on that channel
3. look at the string produced by this.

**Expected behavior:** You should get an emoji or emoji alias

**Actual behavior:** I bunch of weird characters show up

**Version affected:** 2.8.4

### Additional Information
```Java
String topic = EmojiParser.parseToAliases(c.getTopic());
RequestBuffer.request(() -> channel.sendMessage("c.getTopic: "+c.getTopic()+" | Topic: "+topic));
```
For a channel with this topic: ":lock: cenas" 
this code produces this: `c.getTopic: ðŸ”’cenas | Topic: ðŸ”’cenas`

**Comment by GrandPanda** [comment]
The characters returned by Discord4J are correct. You are not outputting in the proper encoding.
