### ISSUE TITLE
Guild#editUserRoles does not add roles to an user.

### ISSUE THREAD

**Issue by KSchaap1994** [austinv11/Discord4J#35]
### Description
Guild#editUserRoles does not add roles to an user.

### Steps to Reproduce
1. Use Guild#editUserRoles to add an existing role to an user

**Expected behavior:** Adding a UserRole to an user

**Actual behavior:** Nothing happened

**Version affected:** 2.4.7

### Additional Information

http://pastie.org/private/5ehb7uc02rov6cxovwol5g#24

**Comment by austinv11** [comment]
I'll also probably add an addRole() method in 2.5 to make this easier.

**Comment by ENMAGames** [comment]
Yea this is pretty complicated I find.
All I would want to do is:
`user.addRoleByID(IGuild, roleID)`
and
`user.removeRoleByID(IGuild, roleID)`

**Comment by grandmind** [comment]
I agree it's a bit over complicated, but it's not that bad. I also can't reproduce this issue. The following code functions perfectly:
```
List<IRole> curRoles = guild.getRolesForUser(user);
curRoles.add(role);
IRole[] roles = curRoles.stream().toArray(IRole[]::new);
guild.editUserRoles(user, roles);
```
where `role`, `guild`, and `user` are correctly defined.

**Comment by KSchaap1994** [comment]
@grandmind - guild#getRolesForUser doesn't exist for me.

**Comment by grandmind** [comment]
@KSchaap1994 Sorry, I was using the latest Dev version. IUser#getRolesForGuild() should be the same thing.
