### ISSUE TITLE
Suggestion: Add Implementation for Categories and System messages

### ISSUE THREAD

**Issue by Vaerys-Dawn** [austinv11/Discord4J#350]
I have noticed that these events are currently missing from the event list and would like them to be added.

## Additional Information
System messages are any message that does not have a 0 for the type field. only messages with types 6 and 7 should be able to be obtained within a guild.  

Type | Value
-- | --
DEFAULT | 0
RECIPIENT_ADD | 1
RECIPIENT_REMOVE | 2
CALL | 3
CHANNEL_NAME_CHANGE | 4
CHANNEL_ICON_CHANGE | 5
CHANNEL_PINNED_MESSAGE | 6
GUILD_MEMBER_JOIN | 7

**Comment by danthonywalker** [comment]
a6f4bbb implements categories in a testable state. There's one known bug with `ICategory#removePermissionsOverride(IRole)` and will be worked out soon. Please test this branch if you can.
