### ISSUE TITLE
Cache not updating after leaving (and joining) a guild

### ISSUE THREAD

**Issue by feldim2425** [austinv11/Discord4J#351]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Cache does not update the roles a user has if the user leaves and re-joins a guild.

### Steps to Reproduce
1. Invite a Bot (that uses Discord4J) into at least 2 Guilds (I didn't test it with 1)
2. Join with a user account both guilds
3. Give the user accounts some roles (and check them with the bot)
4. Leave one of the guilds with the user account
5. Join the same guild again
6. If you check again (with the bot) the user should have more roles than he should have (same roles before he left)

...

**Expected behavior:** The API should update the cache if the user leaves or joins a guild

**Actual behavior:** The API doesn't update the cache and shows the same roles after the user joins again.

**Version affected:** 2.9

### Additional Information
I don't know if that is important but I iterate trough a list of all users from the IGuild#getUsers() Method and check the roles by calling IUser#getRolesForGuild().

**Comment by GrandPanda** [comment]
Fixed by d12a9ac480d1d866f8b9beb0d2ce563f2faf4b9b.
