### ISSUE TITLE
possible issue with 403 forbidden error, and small question about v2.9 deprecation

### ISSUE THREAD

**Issue by alexpmorris** [austinv11/Discord4J#352]
1. I was getting a similar error in v2.8.4, and now in v2.9 as well.  At first I figured it may have been some sort of deprecated request, but since it's still happening in v2.9, I figured I'd report it just in case:

```
[ERROR][RequestBuffer Initial Executor][sx.blah.discord.Discord4J] - Received 403 forbidden error for url https://discordapp.com/api/v6/guilds/342671962214236161/webhooks. If you believe this is a Discord4J error, report this!
```
Besides this "status message", all functionality seems fine.

2. Upon upgrading, I noticed that `event.getGuild().getGeneralChannel()` was deprecated.  
I re-implemented it as `((Guild)event.getGuild()).getGeneralChannel()`, which seems to work fine.  
However, this format appears to be a bit different than the one indicated: 
```@deprecated Use {@link #getDefaultChannel()} instead.```

Just wanted to make sure there's not a better way I should implement this.  Thanks!

**Comment by TsundereBug** [comment]
1. Known bug, not fixable yet as far as I know.
2. General channels are no longer a thing. Default channel might be null because you can delete all channels in a server.

**Comment by alexpmorris** [comment]
Ah geez okay, thanks for clarifying that (on both counts).  I've been already checking `getGeneralChannel()` for null, because I did come across a channel that had deleted their general channel just to clear it out and then couldn't "reset" it to "general".

But somehow I was missing that it's now `getDefaultChannel()`, I think because I found the non-deprecated version in `Guild` when scanning the code and it threw me off.  Thanks again for the clarification.  I'll change over to using `getDefaultChannel()` instead.

**Comment by GrandPanda** [comment]
To provide some more info on the webhook 403, certain features in Discord4J regarding webhooks cause this issue. These features really shouldn't exist and have been removed in the `change/webhooks` branch. However, I am not currently permitted to merge this for the next release because of concerns around removing pre-existing functionality.

**Comment by alexpmorris** [comment]
just wanted to provide a quick update that by using `getDefaultChannel()` I was getting back many different results versus `getGeneralChannel()`, so much so that I was forced to return to using `((Guild)event.getGuild()).getGeneralChannel()`, at least for the time being.  

It seems this is the way the "default channel" works now, which is different than what is return via `getGeneralChannel()`:

>They actually changed this a few weeks ago, the new default channel is now the highest channel a user has access to.
>So whichever channel you want as your default channel for the @everyone role, just make sure it's at the top of your channel list.

*(from a comment here: https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/11489082-change-default-channel)*

Regarding webhooks, I had wondered why it was calling for webhooks, but it does make sense to some degree, as it seems to implement API functionality to create/delete them.  I still use static webhooks for a few things since it's easy to hit up a REST endpoint to serve up some data in a particular guild.  But it's of course no comparison to what can be achieved using Discord4J, and in fact I've been increasingly porting my use of webhooks over to Discord4J instead.

**Comment by GrandPanda** [comment]
There is no such thing as a general channel anymore. Thats why the default channel method returns different results. You should not be accessing internal methods like that. It will be removed in the next release.

**Comment by alexpmorris** [comment]
I appreciate that @GrandPanda and I figured as much.  The problem is that in practice, all the discord servers I'm working with still maintain the premise of a "general" channel, and they may not want to set their "general" channel to the "top" channel (unless discord forces some reason upon them to do so).  As such, it sounds like I'll probably just have them all supply me with their "channel of choice" to use as their "main channel" for interaction, which more often than not, should likely still be called "general".
