### ISSUE TITLE
Downloading attachment

### ISSUE THREAD

**Issue by TodesRitter** [austinv11/Discord4J#353]
Hey,

i tryed to download a attachment with a Bot but Discord sends me a 403(The Authorization token you passed did not have permission to the resource) back.
How can i pass the token ?
Could somebody give me a hint ?
regards

```
	public boolean update(Attachment attachment)
	{
		try
		{
			if (attachment.getFilename().equalsIgnoreCase("cmd.json"))
			{
				downloadUsingNIO(attachment.getUrl(), attachment.getFilename());
				return true;
			}
		} catch (IOException e)
		{
			e.printStackTrace();
		}
		return false;
	}

	private static void downloadUsingNIO(String urlStr, String file) throws IOException
	{
		URL url = new URL(urlStr);
		ReadableByteChannel rbc = Channels.newChannel(url.openStream());
		FileOutputStream fos = new FileOutputStream(file);
		fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
		fos.close();
		rbc.close();
	}
```

**Comment by decyg** [comment]
This is not an issue with the api, look up information about how to use user agents to get a resource from a URL. Or ask the d4j server for help

**Comment by danthonywalker** [comment]
And for future reference, when you create an issue you are given a template. Don't simply erase / ignore that template. We will just ignore and close the issue with no regards to your actual content.

**Comment by TodesRitter** [comment]
will do, thanks and sorry
