### ISSUE TITLE
Detecting if a user is currently streaming

### ISSUE THREAD

**Issue by ENMAGames** [austinv11/Discord4J#36]
It is perfectly possible that right now this functionality is not yet in the official API or that it is in Discord4J and I couldnt find it.
[http://puu.sh/oMl7B/61c2d32d7b.png](http://puu.sh/oMl7B/61c2d32d7b.png)
However if not, it would be great if one could detect this in the future.

In specific: I want to automatically add users that are currently streaming to a role, which is displayed on top of the list, so that users may see it and check out their stream; and that role is removed from them when not streaming anymore.

**Comment by grandmind** [comment]
This is supported in the dev branch for 2.5.
