### ISSUE TITLE
Exception in thread "Typing Status Timer", setTypingStatus crashes because the timer is already cancelled

### ISSUE THREAD

**Issue by NorbiPeti** [austinv11/Discord4J#361]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I get an exception in the Typing Status Timer, then all my code fails at setTypingStatus() with "the timer is already cancelled".

### Steps to Reproduce
1. Use setTypingStatus(true) on a *private* channel and wait

**Expected behavior:**
The typing status gets set as it did before, and the method continues to work.

**Actual behavior:**
The typing status timer crashes after some time and breaks code calling setTypingStatus().

**Stacktrace (if applicable):**
https://pastebin.com/u7Ev2Q2H

**Version affected:**
2.9.1 https://github.com/austinv11/Discord4J/commit/474619a6bef6cda33fe710cf496a16e3a876061a

**Comment by danthonywalker** [comment]
Cannot reproduce. Can you make a simple example that causes the issue?

**Comment by NorbiPeti** [comment]
Okay, so I have a code that basically does this:

```
(On MentionEvent/MessageReceivedEvent)
event.getMessage().getChannel().setTypingStatus(true);
RequestBuffer.request(()->channel.sendMessage(content)).get();
message.getChannel().setTypingStatus(false); //There may be cases where there's no sendMessage()
```

And apparently it works every second try, every other try I get the "Timer already cancelled" exception. The first exception (in the timer thread), occurs only once at first try, directly after my code running without any issues. The second try breaks my code with the "already cancelled" exception at the setTypingStatus(true) call. The third try runs without any issues. Then it alternates between erroring and working.

**Comment by NorbiPeti** [comment]
Found the issue, something I *really* forgot about is that this happens in a private channel. Apparently all we need is to set the typing status to true in a private channel, then wait for the Typing Status Timer to check if the channel is deleted, which throws an exception because private channels don't support `isDeleted()`.

**Comment by danthonywalker** [comment]
Try commit 8f60d66

**Comment by NorbiPeti** [comment]
It works now, thanks!
