### ISSUE TITLE
Updating a channel's topic moves it out from it's category

### ISSUE THREAD

**Issue by NorbiPeti** [austinv11/Discord4J#362]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Using IChannel.changeTopic() removes the channel from it's category, leaving it uncategorized.

### Steps to Reproduce
1. Make sure the target channel is in a category
2. Use IChannel.changeTopic() on the target channel

**Expected behavior:**
The channel stays in it's place, while it's topic is changed to the new value.

**Actual behavior:**
The channel's topic gets set, and it gets moved out of it's category, making it uncategorized.

**Stacktrace (if applicable):**
-

**Version affected:**
2.9.1 https://github.com/austinv11/Discord4J/commit/474619a6bef6cda33fe710cf496a16e3a876061a

**Comment by danthonywalker** [comment]
Already fixed as of 72dad28
