### ISSUE TITLE
Website SSL Certificate expired

### ISSUE THREAD

**Issue by hkuhn42** [austinv11/Discord4J#366]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [ ] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The ssl certificate of the website expired today. Not a software issue but thought i let you know...

### Steps to Reproduce
open https://discord4j.com/ in any modern browser
...

**Expected behavior:** [What was supposed to happen]

**Actual behavior:** [What actually happened]

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of Discord4J]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by austinv11** [comment]
The certificate has now been renewed. Thanks for letting us know. However, I'd prefer these type of issues to be posted on the https://github.com/Discord4J/Discord4J-Website/ repo or simply mentioned on our discord server.
