### ISSUE TITLE
getMessageHistoryIn(long beginID, long endID, int maxCount) dosen't respect maxCount for most values.

### ISSUE THREAD

**Issue by usbpc102** [austinv11/Discord4J#369]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
[`Channel.getMessageHistoryIn(long beginID, long endID, int maxCount)`](https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/handle/impl/obj/Channel.java#L288) dosen't respect `maxCount`  as expected. Requesting 101 messages returns 199 Messages. 101 is the smallest number this happens with; Requesting 101-198 all return 199 Messsages. Requesting 201-297 return 298 messages and so on. 

I would expect to get exactly as many messages as specified using `maxCount` if there are that many messages in the range specified.

This bug also effects other methodes that rely on [`Channel.getMessageHistoryIn(long beginID, long endID, int maxCount)`](https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/handle/impl/obj/Channel.java#L288) like [`Channel.getMessageHistoryTo(LocalDateTime endDate, int maxCount)`](https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/handle/impl/obj/Channel.java#L257).

### Steps to Reproduce
1. Call `Channel.getMessageHistoryIn(long beginID, long endID, int maxCount)` with maxCount = 101 on a channel that has 199 or more messages that are in the range between beginID and endID.
2. Look at the returned MessageHistory and see that there are 199 Messages in there

**Expected behavior:** Get a MessageHistory containing 101 Messages

**Actual behavior:** Getting a MessageHistory containing 199 Messages

**Version affected:** Discord4J v2.9.2 49a6f26

**Comment by danthonywalker** [comment]
Try out 444a127. I'm not confident in the fix, however, so a bit more testing would be really helpful.
