### ISSUE TITLE
NullPointerException when a message is sent by the bot

### ISSUE THREAD

**Issue by Shadorc** [austinv11/Discord4J#377]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
A NullPointerException is thrown when the max message cache count is set to 0, the bot doesn't have permission to read message history and a message is sent by the bot.

### Steps to Reproduce
1. Set max message cache count to 0
2. Don't allow to read message history
3. Send a message with the bot

**Expected behavior:** Nothing

**Actual behavior:** NullPointerException is thrown.

**Stacktrace (if applicable):** https://pastebin.com/zEmsZzFH

**Version affected:** Discord4J v2.9.3-SNAPSHOT 98b84f2

### Additional Information
This error occurred following the correction of this issue:
https://github.com/austinv11/Discord4J/issues/376

**Comment by danthonywalker** [comment]
Paste is private

**Comment by Shadorc** [comment]
It's now public, sorry.
