### ISSUE TITLE
Listening and Watching are reversed

### ISSUE THREAD

**Issue by egold555** [austinv11/Discord4J#380]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [  ] This issue specifically has something to do with Discord4J
* [  ] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When calling changePresence on the discord client, setting the ActivityType to LISTENING makes the bot display Watching, and when you set ActivityType to WATCHING, it changes the test to Listening. 

### Steps to Reproduce
1. Create a simple bot
2. call _client.changePresence(StatusType.DND, ActivityType.WATCHING, "a movie");

...

**Expected behavior:** The bot should be on DND and have the status text of Watching a movie.

**Actual behavior:** The bots on DND but its status text gets changed to Listening a movie.

**Stacktrace (if applicable):** No errors occur.

**Version affected:** Discord4j-dev-2.9.3-ga7394f3-5-shaded (Latest Dev version as of writing this bug report)

### Additional Information
ActivityType.STREAMING causes an exception, but I think that's for another bug report.

**Comment by danthonywalker** [comment]
STREAMING is intended. Use a different method for that.

**Comment by egold555** [comment]
The streaming thing is somewhat related but watching is listening is reversed
