### ISSUE TITLE
I'm having trouble counting the number of reactions since the last update.

### ISSUE THREAD

**Issue by HammerKick** [austinv11/Discord4J#383]
# **Description**

I'm having trouble counting the number of reactions on a post since the last update, with all the possible ways to do it.

# **Steps to reproduce**

1- I boot up the bot, I post a message, I put a reaction. The counter goes to 1.
2- Someone else decides to use the same reaction on the same post. The counter stays at 1.
3- I reboot the bot. I remove my reaction, the counter goes back to 1. I put the reaction back, it increases to 2.

# **Additional information**

Nope.

**Comment by finreinhard** [comment]
I have the same issue. The counter sticks to 1 on new messages :/
