### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Hemant0601** [austinv11/Discord4J#388]
### Description
Unable to build app after using disk4j gradle
How I am using is
compile "com.github.austinv11:Discord4J:2.9.3"

My IDE details
Android studio 3.0.0

My gradle version 

classpath 'com.android.tools.build:gradle:3.0.1'

### Steps to Reproduce
1. Just add compile "com.github.austinv11:Discord4J:2.9.3"
	in a newly created project with the above IDE and gradle configuration 
2. Try to run the build in device

**Expected behavior:** 

Has to run without errors

**Actual behavior:** 

Not building properly 

Getting following errors

Warning:Ignoring InnerClasses attribute for an anonymous inner class
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/hemant/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-client/9.4.8.v20171121/e93cac2ce46e81ee8b36288cf7e19d3bac82d536/jetty-client-9.4.8.v20171121.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/eclipse/jetty/client/MultiplexConnectionPool.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/hemant/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-client/9.4.8.v20171121/e93cac2ce46e81ee8b36288cf7e19d3bac82d536/jetty-client-9.4.8.v20171121.jar
Error:com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/hemant/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-client/9.4.8.v20171121/e93cac2ce46e81ee8b36288cf7e19d3bac82d536/jetty-client-9.4.8.v20171121.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/hemant/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-client/9.4.8.v20171121/e93cac2ce46e81ee8b36288cf7e19d3bac82d536/jetty-client-9.4.8.v20171121.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/hemant/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty/jetty-client/9.4.8.v20171121/e93cac2ce46e81ee8b36288cf7e19d3bac82d536/jetty-client-9.4.8.v20171121.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/eclipse/jetty/client/MultiplexConnectionPool.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

Same as above

**Version affected:** 
 2.9.3

### Additional Information

Trying to run Discord to create a PTT app

**Comment by austinv11** [comment]
So none of that is directly pointing to Discord4J, but instead to jetty. If you read the stack trace you will notice that it is saying you need a minimum sdk of 26 as this project uses java 8 features.

**Comment by Hemant0601** [comment]
The jetty framework is build inside Discord4J and are you saying that the Discord feature cannot be used in any app below sdk 26 ? Because the core discord app works under version 26. Please provide the info, thanks

**Comment by decyg** [comment]
The D4J project requires a bare minimum of Java 8 to be used as many J8 lang features are used within the API. The official discord android app is not affiliated with this (Discord4J) project in any way and their development of it is closed source. I'm not an android developer so i can't say for sure if D4J would work on android even under the J8 compatibility released mid last year

**Comment by Hemant0601** [comment]
Ya, thanks. I just wanna confirm that.
