### ISSUE TITLE
Illegal reflective access operation in Java 9

### ISSUE THREAD

**Issue by Harieo** [austinv11/Discord4J#389]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
An illegal reflective access operation warning happens when attempting to build and login an instance of IDiscordClient with the ClientBuilder. I recently upgraded to Java 9 from Java 8 where I didn't get this error using the same code.

### Steps to Reproduce
1. Use the ClientBuilder to build an instance of IDiscordClient
2. Log the IDiscordClient in
3. Receive the error
...

**Expected behavior:** [What was supposed to happen]
All my code attempts to do is build the client, log it in then send a success message to console if IDiscordClient#isLoggedIn() is true and an error message if this method is false. 

**Actual behavior:** [What actually happened]
The warning is printed in console and my error message (from above) is sent after it.

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]
https://pastebin.com/r9xaBkTy - From console, the printed line about the bot not logging in is mine for testing

**Version affected:** [The version of Discord4J]
2.9.3

**Comment by danthonywalker** [comment]
There's nothing particularly wrong here. It doesn't break anything and we can't control it anyway.
