### ISSUE TITLE
onReady event getGuild size is inconsistant

### ISSUE THREAD

**Issue by Vaerys-Dawn** [austinv11/Discord4J#40]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
getting amount of Guilds a bot is connected with within onReadyEvent is inconsistent and often returns a 0 even if the bot has been confirmed to be connected to a Guild.

### Steps to Reproduce
1. Make sure that the bot is connected to a Guild and shows up in the User list.
2. Print out event.getClient().getGuilds().size();
3. Run Bot, Repeat about 10 times

...

**Expected behavior:** Consistantly return the amount of Guilds the bot is connected to

**Actual behavior:** bot is connected to 2 Guild's, performing the steps above can return 0 on many occasions and 1 on some, never 2.

**Stacktrace (if applicable):** N/a

**Version affected:** dev-SNAPSHOT (31aef0e)

### Additional Information
Server 1:
![image](https://cloud.githubusercontent.com/assets/5305116/15454221/7e9ed5b2-2075-11e6-951e-93aa9ad022d5.png)
Server 2:
![image](https://cloud.githubusercontent.com/assets/5305116/15454227/a0eea2e6-2075-11e6-968b-659edc3894d0.png)

**Comment by manuelgu** [comment]
Known. Listen to the `GuildCreateEvent` in 2.4.x. In future versions (`2.5`) the ReadyEvent will fire once the bot has joined all guilds.

**Comment by austinv11** [comment]
I have tried multiple times but I am unable to reproduce on the dev branch. Try setting your logger to the TRACE level and pastebin the log (with personal info removed if necessary). You should see something like this:
```
...
17:30:08.255 [Request Builder Async Executor] INFO  sx.blah.discord.Discord4J - Connected to 2 guilds.
17:30:08.256 [Request Builder Async Executor] TRACE sx.blah.discord.Discord4J - Initially loaded 0/2 guilds.
...
17:30:09.936 [WebSocketClient@1840903588-16] DEBUG sx.blah.discord.Discord4J - New guild has been created/joined! "NAME" with ID ID.
...
17:30:09.947 [Event Dispatch Thread] TRACE sx.blah.discord.Discord4J - Loaded 1/2 guilds.
17:30:10.015 [WebSocketClient@1840903588-16] DEBUG sx.blah.discord.Discord4J - New guild has been created/joined! "NAME" with ID ID.
17:30:10.016 [Event Dispatch Thread] TRACE sx.blah.discord.Discord4J - Loaded 2/2 guilds.
```
It shows if Discord4J is identifying the guilds correctly.

**Comment by Auramaster13** [comment]
unfortunately i have no idea how to set up the logger correctly for my build. and so i cant really get that for you unless i figure it out, i have narrowed the issue down slightly in that it only affects the onReadyEvent as i performed the same check in the onMessageRecievedEvent and received a value of 2

**Comment by Auramaster13** [comment]
http://pastebin.com/KN7wRkan
