### ISSUE TITLE
Received 404 error

### ISSUE THREAD

**Issue by egold555** [austinv11/Discord4J#403]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I got this: 19:55:39.889: [ERROR][Event Dispatcher Handler][sx.blah.discord.Discord4J] - Received 404 error, please notify the developer and include the URL (https://discordapp.com/api/v6/guilds/415986146871345152/members/398304748349947904)

### Steps to Reproduce
Honestly I am not sure what caused this error. I just started up my bots code from where I left off yesterday and got the exception.

...

**Expected behavior:** I expected no errors to be on the console (This error did not happen yesterday with the bot. 3/2/18)

**Actual behavior:** I expected my bot to work as it did yesterday

**Stacktrace (if applicable):** No stack trace. Just error stated above in the Description.

**Version affected:** 2.9.3

### Additional Information
This just started happening as of 3/3/2018. Yesterday 3/2/2018 this error did not appear in my console. From my testing the bot seems to be working totally fine. I do not know why this error happened.

**Comment by xaanit** [comment]
This should only appear when you're trying to do something to a member who isn't in the server. Make sure you're not using a method like `IDiscordClient#getUserByID` to grab a user that's in the guild, and then trying to kick them (or similar).

**Comment by egold555** [comment]
OK. Thanks so much! Ill double check my code.
