### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by UnderKoen** [austinv11/Discord4J#404]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When I try to login with the bot the program crashes. I'm made a sort of jar runner that runs the bot. In the editor runner it all works but when I run it in terminal it's crashes.

### Steps to Reproduce
1. Make a launcher with URLClassLoader
2. Launch a bot with this launcher outside the editor
3. Crash?

**Expected behavior:** [What was supposed to happen]
It should of logged in and continued without a problem
**Actual behavior:** [What actually happened]
It threw a java.lang.VerifyError,
**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]
https://pastebin.com/xPhV4rrd
**Version affected:** [The version of Discord4J]
2.10.0
### Additional Information
My code: https://github.com/UnderKoen/UnderBot

**Comment by austinv11** [comment]
This is an external issue related to your classloading somehow as it is reporting that WebhookCreateEvent is not a subclass of Event, which it most certainly is.

**Comment by UnderKoen** [comment]
Found why it happens it not a external issue :/ . in https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/modules/ModuleLoader.java on line 301 you ignore the ClassNotFoundException that why it's happend's not totally sure.

**Comment by ArsenArsen** [comment]
Still is an external issue. Don't load shaded jars as modules.

**Comment by austinv11** [comment]
That is not the issue because https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/modules/ModuleLoader.java#L286 would be called in the case of such an exception.
