### ISSUE TITLE
Change sendFile parameter to InputStream

### ISSUE THREAD

**Issue by Elnathbeta** [austinv11/Discord4J#41]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
It would be nice if the `sendFile` function accepted an `InputStream` as parameter instead of a `File`. `File` classes are difficult to use inside of a jar file (best solution I found on google was to copy the file from the jar to a temporary location) and it would also give you the possibility of sending images from an url or any other resource

**Comment by oopsjpeg** [comment]
I'm working on this issue. What should the name of the file sent be called? Or should I add a parameter for that?

**Comment by oopsjpeg** [comment]
i've finished the issue under https://github.com/austinv11/Discord4J/pull/80
