### ISSUE TITLE
Getting audio data from a voicechannel

### ISSUE THREAD

**Issue by devidation** [austinv11/Discord4J#44]
Hello.
I can't seem to get audio right. I have managed to play music and stuff correctly queueing a file.
Now I would like to make something like an echo bot by getting the received audio and sending it back through the bot. However I can't get this to work properly.

I'm using the VoiceUserSpeakingEvent.
When it triggers I get the client's audio channel and take It's audiodata.
I then try to put the audio data in an inputstream to send it to the audiochannel's queue method.
However it seems to already break at the getAudioData() method.

Could anyone shed some light on this particular problem?
Thanks in advance!

**Comment by grandmind** [comment]
Audio receiving is not supported at this time.
