### ISSUE TITLE
IChannel#getModifiedPermissions for private channel throws uncaught exception

### ISSUE THREAD

**Issue by Sadillac** [austinv11/Discord4J#47]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Trying to get the bot permissions for private channel results in an exception.

### Steps to Reproduce
1. Send bot a private message.
2. React with bot and try to get permissions for IMessage#getChannel
3. Exception

**Expected behavior:**
The permissions for this private channel. For example the Permissions.SEND_MESSAGES.

**Actual behavior:** 
The method breaks with an exception.

**Stacktrace (if applicable):** 
http://pastebin.com/8j1SQcbj
results in
http://pastebin.com/RF4FUN8L

**Version affected:** 
f8144af

**Comment by theIglooo** [comment]
https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/handle/impl/obj/PrivateChannel.java#L36
That's how it's supposed to work, private channels don't have permissions which is why it throws UnsupportedOperation.
