### ISSUE TITLE
Threads not properly released

### ISSUE THREAD

**Issue by xunkar** [austinv11/Discord4J#5]
Hello,
I've noticed that ClientBuilder.login() creates 3 different threads, but those threads are never stopped when calling logout() can you look into it?

**Comment by xunkar** [comment]
After investigating, it turns out that the problem comes from the WebSocket library (WebSocketClient.close() not terminating its own threads), considering the number of issues raised by this library, maybe using something else would be better.

**Comment by austinv11** [comment]
What do you mean that the threads aren't stopped?

**Comment by xunkar** [comment]
Here in this first screen you can see the 3 highlighted threads being created by the call to ClientBuilder.login()

![login](https://cloud.githubusercontent.com/assets/329857/12867746/2514cc9a-ccf6-11e5-85dd-e0c009845b7d.jpg)

And there, you can see that ClientBuilder.logout() properly terminates 'WebsocketWriteThread' but the 3 problematic threads are left hanging and never stops.

![logout](https://cloud.githubusercontent.com/assets/329857/12867753/62fa0d5e-ccf6-11e5-8003-452fec0dbd54.jpg)

**Comment by austinv11** [comment]
Just note that the 'pool-2-thread-1' thread will still appear to be running but it will be on a WAIT state, so it shouldn't do any harm.

**Comment by xunkar** [comment]
Then the issue remains. Every thread must be properly terminated when logging out. Alternatively you could add a method to gracefully shutdown all active thread if you want to differentiate between logging out and shutting down. Even with your proposed fix, threads will not terminate and even TestBot hangs.
![hang](https://cloud.githubusercontent.com/assets/329857/12868324/3773d8be-cd04-11e5-8fdc-398051a0c2fb.jpg)
