### ISSUE TITLE
Discord4J Dev Build Login Exception

### ISSUE THREAD

**Issue by ColeTheKing** [austinv11/Discord4J#50]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Logging in a bot using the ClientBuilder and.withToken("TOKEN").login(); throws an exception:
`java.lang.NoClassDefFoundError: sx/blah/discord/api/IListener` 

### Steps to Reproduce
1. Login a bot using `client = new ClientBuilder().withToken("TOKEN").login();`
2. Get exception.

...

**Expected behavior:** Login the bot and proceed to listen for commands.

**Actual behavior:** Uncaught exception thrown at login.

**Stacktrace (if applicable):** http://pastebin.com/JDRnrR2b

**Version affected:** 2.5.0-SNAPSHOT (Latest dev build)

### Additional Information
None.

**Comment by grandmind** [comment]
How are you getting Discord4J? You're missing a class in the library itself.

**Comment by ColeTheKing** [comment]
I have the Jar from the latest build added as a dependency. I've switched from using the maven dependency specified in the pom.xml file to the jar, could there had been an error in the process of switching over perhaps?

**Comment by grandmind** [comment]
Depending on your IDE, it may be using both at once. For Intellij, right click the pom.xml, select maven, and select reimport.

**Comment by ColeTheKing** [comment]
I didn't necessarily want to switch from Maven, but I'm not sure if it's possible to edit the dependency to match the dev branch instead of the master branch. If that's possible I'll do it that way, but I'm unfamiliar with how to do so.

**Comment by grandmind** [comment]
Change the version in Maven to either a commit hash like `35f085b` or to `dev-SNAPSHOT` for the latest commit.

**Comment by ColeTheKing** [comment]
Doesn't seem to work, tried both the commit hash and SNAPSHOT. I'm currently running Intellij with it's built in maven. I think Intellij is using maven 2, which I could've sworn is an older version and out of date - though I'm not entirely sure. Thanks for your help thus far, @grandmind .

**Comment by grandmind** [comment]
@ColeTheKing 
For me, IntelliJ sometimes reports an error when using dev-SNAPSHOT when there is none. It says it can't find the dependency, but it still downloads it just fine. Check if this is the case.

**Comment by ColeTheKing** [comment]
Seems to be that this is the case, though I'm still getting the same error as before. The new library is `com.github.austinv11:Discord4j:dev-2.4.9-g82c2bb4-70`, which matches the latest commit.

**Comment by ColeTheKing** [comment]
Alright well, I made a new project completely and it seems to be working fine, so this isn't an issue with Discord4J itself. I'll go ahead and close this now and just re-arrange my project. Thanks for the assistance @grandmind .

**Comment by LolDatSec** [comment]
Maven rebuild or clean might have fixed that.
