### ISSUE TITLE
Are you still on the project

### ISSUE THREAD

**Issue by Jeje2201** [austinv11/Discord4J#55]
Hi, this has nothnig to do with "discord4J" but idk how to find a way to speak to you so I use the last topic you were on to ask this, but because of new mobs like bunnies, shulker, etc.. your "lootplus" plugin don't work, I mean it work for drops on normal mobs, but if a player kill new mobs, you get this error : http://prntscr.com/bk8cut . Is there a way to update it with new mobs please ?

**Comment by phantamanta44** [comment]
You can PM him on CurseForge [here](http://minecraft.curseforge.com/members/austinv11). Please don't open issues on random repositories—these aren't exactly meant to be used as IM.

**Comment by ReaperDeath** [comment]
He stopped supporting Lootplus early 2014.

**Comment by austinv11** [comment]
http://dev.bukkit.org/bukkit-plugins/lootplus/#c26
