### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by LolDatSec** [austinv11/Discord4J#59]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
[Description of the issue]
ConcurrentModificationException when trying to send a private message to a user.
### Steps to Reproduce
1. Try to send a private message
2. {Unknown}
3. Exception?
...

**Expected behavior:** Send the PM properly.

**Actual behavior:** ConcurrentModificationException - And probably did not send the message.

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]
http://pastebin.com/bkKhmjxK

**Version affected:** Latest commit on dev

### Additional Information
[Any other information that may be able to help me with the problem]
This bug ticket is poorly written as I do not have much knowledge of how this happened, just popped up when someone tried to use my bot.
(Don't look at my github repo for my bot, I haven't commited in ages.)

**Comment by phantamanta44** [comment]
oh shoot that's my code
