### ISSUE TITLE
Implement Sharding

### ISSUE THREAD

**Issue by austinv11** [austinv11/Discord4J#67]
I have been meaning to do this for awhile.

Some requirements of this feature would have to include:
- a ClientBuilder#withShards() method
- Some way to find out which shard an event was dispatched from (Event#getShard()?)
- Possibly a way hotswap shard size (which means reconnecting the websocket). It may be necessary to keep the old connection alive until the new gateway is ready to make sure events aren't missed if the session ends up being invalid.

**Comment by chrislo27** [comment]
If I remember correctly, sharding was implemented on its branch but you were having trouble with rate limits when connecting (I think). The rate limit for connections is one every five seconds. https://github.com/hammerandchisel/discord-api-docs/issues/17#issuecomment-243030925
