### ISSUE TITLE
Implement Audio Receiving

### ISSUE THREAD

**Issue by austinv11** [austinv11/Discord4J#68]
Audio receiving would be nice to have, however this has low priority for me. It is a stretch goal for 2.6 but it is entirely possible that it won't be implemented by then.

This feature would need:
- Per-user audio
- A utility to combine audio
- It should utilize `AudioManager` in order to allow for one to subscribe an `IAudioReceiver` to receive data in real time as well as providing a method which returns an `AudioInputStream`
- It would be useful to have the ability to determine the format of the received audio (i.e. opus, pcm, etc)

**Comment by BurakDev** [comment]
Already implemented by #71 ?

**Comment by GrandPanda** [comment]
Technically yes, but it was never merged into master/released and it likely won't be soon. Portions of it may need to be reworked after websocket-rewrite (a bigger priority).
