### ISSUE TITLE
Error GLIBC_2.14

### ISSUE THREAD

**Issue by manercraft** [austinv11/Discord4J#74]
### Description
When I start my bot, I got this error 
https://gyazo.com/798d475e7caee63196a4b596a63c5dd7.png

###
Start my bot

**Expected behavior:** Bot start without error

**Actual behavior:** Bot start and crash

**Stacktrace (if applicable):** https://gyazo.com/798d475e7caee63196a4b596a63c5dd7.png

**Version affected:** 2.5.1

### Additional Information
I'm on Linux (Debian 7)

**Comment by phantamanta44** [comment]
You need to install the libc6 package. `sudo apt-get install libc6` should do the trick.

**Comment by manercraft** [comment]
Already done
https://gyazo.com/277c1d6f82666d9ed364cbf2604a087f.png

**Comment by phantamanta44** [comment]
Can you show the results of `apt-cache show libc6`?

**Comment by manercraft** [comment]
https://gyazo.com/d8c93978d5b5f412e1959289f5df53aa.png

**Comment by phantamanta44** [comment]
It looks like Debian-stable doesn't provide libc6 > 2.13, which means you'll probably need to switch to the unstable/testing branch for this one package. Check out this article: http://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing

Alternatively, you can upgrade your entire distro to jessie/stretch, but that takes a bit more work.

**Comment by manercraft** [comment]
My machine is completely KO I ended ticket. Thank for try to help me :)
