### ISSUE TITLE
Re-order roles doesn't check all the necessary permissions

### ISSUE THREAD

**Issue by austinv11** [austinv11/Discord4J#77]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Attempting to move a role higher than the user's current role will result in a DiscordException rather than a MissingPermissionsException.

### Steps to Reproduce
1. Re order a role to a position higher than the bot's

**Expected behavior:** A MissingPermissionsException is thrown

**Actual behavior:** A DiscordException is thrown

**Stacktrace (if applicable):** https://puu.sh/qaPm1/cf45449a0d.png

**Version affected:** [The version of Discord4J]

**Comment by oopsjpeg** [comment]
working on a fix!
