### ISSUE TITLE
Maven don't recognized version 2.5.2

### ISSUE THREAD

**Issue by manercraft** [austinv11/Discord4J#83]
### Description
The version 2.5.2 isn't recognized with Maven

**Expected behavior:** No error

**Actual behavior:** Error

**Stacktrace (if applicable):** Missing artifact com.github.austinv11:Discord4j:jar:2.5.2

**Version affected:** 2.5.2

### Additional Information
I use Maven with eclipse

**Comment by austinv11** [comment]
I am unable to reproduce this on intellij, you should try [checking eclipse's settings](http://stackoverflow.com/a/4264774)
