### ISSUE TITLE
Reconnection Attempt Timed Out

### ISSUE THREAD

**Issue by theIglooo** [austinv11/Discord4J#93]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The reconnect times out and doesn't reattempt afterwards.

### Steps to Reproduce
1. Let D4J attempt to reconnect

...

**Expected behavior:** It reconnects or fails and tries again.

**Actual behavior:** It times out and never tries again

**Stacktrace (if applicable):** http://hastebin.com/imekagafer.avrasm

**Version affected:** 2.5.4 / dev as of writing this

### Additional Information
Seemingly random, instead of reconnecting it just times out, process isn't stopped either.

This is popping up more and more so an issue will make it easier to keep track of.

**Comment by ArsenArsen** [comment]
Ocurred to my bot multiple times. Had to reboot him after I noticed.. But yeah I think this is high priority.

**Comment by pangeacake** [comment]
Occurs for me as well.

**Comment by theIglooo** [comment]
https://gist.github.com/theIglooo/c6dd54193cbd52d33501d2460c34cc57
happened to chris earlier as well
i think it's angry

**Comment by austinv11** [comment]
The latest dev commits *should* fix it

**Comment by ChrisVega** [comment]
https://gist.github.com/ChrisVega/8815d16be7546f8180f6bf9f0be37fe3
Not quite unfortunately.

**Comment by theIglooo** [comment]
Commit: 7934555
```
2016-08-24 19:32:33 [WebSocketClient@1409160703-23] DEBUG sx.blah.discord.Discord4J - Websocket disconnected. Exit Code: 1001. Reason: null.
2016-08-24 19:32:33 [WebSocketClient@1409160703-23] INFO  sx.blah.discord.Discord4J - Attempting to reconnect...
2016-08-24 19:32:34 [WebSocketClient@1409160703-23] INFO  sx.blah.discord.Discord4J - Reconnected to the Discord websocket.
```
Bot stops responding after that.

**Comment by theIglooo** [comment]
```
2016-08-26 13:19:23 [WebSocketClient@1409160703-18] DEBUG sx.blah.discord.Discord4J - User "Capsule-" changed status to GAME (name=DOTA 2, url=null).
2016-08-26 13:19:23 [WebSocketClient@1409160703-21] DEBUG sx.blah.discord.Discord4J - Websocket disconnected. Exit Code: 1006. Reason: WebSocket Read EOF.
2016-08-26 13:19:23 [WebSocketClient@1409160703-21] INFO  sx.blah.discord.Discord4J - Attempting to reconnect...

Process finished with exit code 0
```
Still on 7934555

**Comment by robot-rover** [comment]
This is really screwed up for me now:
http://hastebin.com/ucobatazec.avrasm

**Comment by Dragorn421** [comment]
I'm using 2.5.4.
I had this problem too, multiple times:
```
30-08-16	22:41:04	[WebSocketClient@839998248-16]	INFO	sx.blah.discord.Discord4J	Attempting to reconnect...
30-08-16	22:41:05	[WebSocketClient@839998248-16]	INFO	sx.blah.discord.Discord4J	Reconnected to the Discord websocket.
30-08-16	22:41:42	[Discord4J WebSocket Heartbeat Executor]	WARN	sx.blah.discord.Discord4J	Connection timed out at 41250ms
30-08-16	22:41:42	[Discord4J WebSocket Heartbeat Executor]	INFO	sx.blah.discord.Discord4J	Attempting to reconnect...
30-08-16	22:42:10	[Reconnection Timer]	ERROR	sx.blah.discord.Discord4J	Reconnection attempt timed out.
```
I'm not sure this is directly related but I'm still putting it here (also happens multiple times): http://pastebin.com/D3b6NB1s

**Comment by ChrisVega** [comment]
These changes seemed to have fixed reconnecting still testing but DiscordDisconnectedeven fires, logout doesn't cause it to reconnect, and it can reconnect on internet outages. Haven't found any issues yet.

https://gist.github.com/ChrisVega/266d5fecde507616da4f81051b895297
